#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraLensTimer_Countdown

#include "Basic.hpp"

#include "BP_CameraLensTimer_Countdown_classes.hpp"


namespace SDK
{

// Function BP_CameraLensTimer_Countdown.BP_CameraLensTimer_Countdown_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CameraLensTimer_Countdown_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CameraLensTimer_Countdown_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

