#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FogVolume

#include "Basic.hpp"

#include "BP_FogVolume_classes.hpp"
#include "BP_FogVolume_parameters.hpp"


namespace SDK
{

// Function BP_FogVolume.BP_FogVolume_C.ExecuteUbergraph_BP_FogVolume
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FogVolume_C::ExecuteUbergraph_BP_FogVolume(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "ExecuteUbergraph_BP_FogVolume");

	Params::BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FogVolume.BP_FogVolume_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FogVolume_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FogVolume.BP_FogVolume_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_FogVolume_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FogVolume.BP_FogVolume_C.SetScalarOnFogMaterial
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FogVolume_C::SetScalarOnFogMaterial(float Value, class FName Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "SetScalarOnFogMaterial");

	Params::BP_FogVolume_C_SetScalarOnFogMaterial Parms{};

	Parms.Value = Value;
	Parms.Name_0 = Name_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FogVolume.BP_FogVolume_C.UpdateMaterial
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FogVolume_C::UpdateMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "UpdateMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FogVolume.BP_FogVolume_C.SetVectorOnFogMaterial
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FLinearColor                     Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FogVolume_C::SetVectorOnFogMaterial(const struct FLinearColor& Value, class FName Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "SetVectorOnFogMaterial");

	Params::BP_FogVolume_C_SetVectorOnFogMaterial Parms{};

	Parms.Value = std::move(Value);
	Parms.Name_0 = Name_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FogVolume.BP_FogVolume_C.updateParticle
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FogVolume_C::UpdateParticle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FogVolume_C", "updateParticle");

	UObject::ProcessEvent(Func, nullptr);
}

}

