#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusDropDownAnchor

#include "Basic.hpp"

#include "ButtonStyleMinusBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-DropDownAnchor.ButtonStyle-DropDownAnchor_C
// 0x0000 (0x0AA8 - 0x0AA8)
class UButtonStyleMinusDropDownAnchor_C final : public UButtonStyleMinusBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-DropDownAnchor_C">();
	}
	static class UButtonStyleMinusDropDownAnchor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusDropDownAnchor_C>();
	}
};
static_assert(alignof(UButtonStyleMinusDropDownAnchor_C) == 0x000008, "Wrong alignment on UButtonStyleMinusDropDownAnchor_C");
static_assert(sizeof(UButtonStyleMinusDropDownAnchor_C) == 0x000AA8, "Wrong size on UButtonStyleMinusDropDownAnchor_C");

}

