#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Buff_Offlane_Regen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Buff_Offlane_Regen.GC_Buff_Offlane_Regen_C
// 0x0010 (0x0850 - 0x0840)
class AGC_Buff_Offlane_Regen_C final : public AOrionGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0840(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_Buff_Offlane_Regen(int32 EntryPoint);
	void K2_WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, class UParticleSystemComponent* LoopingParticleSystem, const TArray<class UParticleSystemComponent*>& AdditionalParticleSystem, class UNiagaraComponent* LoopingNiagaraParticleSystem, const TArray<class UNiagaraComponent*>& AdditionalNiagaraParticleSystems);
	void K2_OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, class UParticleSystemComponent* ApplicationParticleSystem, const TArray<class UParticleSystemComponent*>& AdditionalParticleSystems, class UCameraShake* ApplicationCameraShakeInstance, class UNiagaraComponent* ApplicationNiagaraParticleSystem, const TArray<class UNiagaraComponent*>& AdditionalNiagaraParticleSystems);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Buff_Offlane_Regen_C">();
	}
	static class AGC_Buff_Offlane_Regen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Buff_Offlane_Regen_C>();
	}
};
static_assert(alignof(AGC_Buff_Offlane_Regen_C) == 0x000010, "Wrong alignment on AGC_Buff_Offlane_Regen_C");
static_assert(sizeof(AGC_Buff_Offlane_Regen_C) == 0x000850, "Wrong size on AGC_Buff_Offlane_Regen_C");
static_assert(offsetof(AGC_Buff_Offlane_Regen_C, UberGraphFrame) == 0x000840, "Member 'AGC_Buff_Offlane_Regen_C::UberGraphFrame' has a wrong offset!");

}

