#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Item_Aura_HealthRegen

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GC_Item_Aura_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Item_Aura_HealthRegen.GC_Item_Aura_HealthRegen_C
// 0x0010 (0x08C0 - 0x08B0)
class AGC_Item_Aura_HealthRegen_C final : public AGC_Item_Aura_C
{
public:
	struct FLinearColor                           HealthRegenColor;                                  // 0x08B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Item_Aura_HealthRegen_C">();
	}
	static class AGC_Item_Aura_HealthRegen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Item_Aura_HealthRegen_C>();
	}
};
static_assert(alignof(AGC_Item_Aura_HealthRegen_C) == 0x000010, "Wrong alignment on AGC_Item_Aura_HealthRegen_C");
static_assert(sizeof(AGC_Item_Aura_HealthRegen_C) == 0x0008C0, "Wrong size on AGC_Item_Aura_HealthRegen_C");
static_assert(offsetof(AGC_Item_Aura_HealthRegen_C, HealthRegenColor) == 0x0008B0, "Member 'AGC_Item_Aura_HealthRegen_C::HealthRegenColor' has a wrong offset!");

}

