#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GreenBuff_AnimBP

#include "Basic.hpp"

#include "GreenBuff_AnimBP_classes.hpp"
#include "GreenBuff_AnimBP_parameters.hpp"


namespace SDK
{

// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.ExecuteUbergraph_GreenBuff_AnimBP
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGreenBuff_AnimBP_C::ExecuteUbergraph_GreenBuff_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "ExecuteUbergraph_GreenBuff_AnimBP");

	Params::GreenBuff_AnimBP_C_ExecuteUbergraph_GreenBuff_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGreenBuff_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "BlueprintUpdateAnimation");

	Params::GreenBuff_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_ApplyAdditive_AC16A6394EBB9E30B561E9822F30F92F
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_ApplyAdditive_AC16A6394EBB9E30B561E9822F30F92F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_ApplyAdditive_AC16A6394EBB9E30B561E9822F30F92F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendListByBool_59D4675041BCDB819A047A810F1F939D
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendListByBool_59D4675041BCDB819A047A810F1F939D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendListByBool_59D4675041BCDB819A047A810F1F939D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendListByBool_654A03224DFDB39A50CC5FB59BE902B8
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendListByBool_654A03224DFDB39A50CC5FB59BE902B8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendListByBool_654A03224DFDB39A50CC5FB59BE902B8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendSpacePlayer_C8E5493240BC1750840A83B89E1AD040
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendSpacePlayer_C8E5493240BC1750840A83B89E1AD040()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_BlendSpacePlayer_C8E5493240BC1750840A83B89E1AD040");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_RotateRootBone_D6E8C6014B5076050F4A5CA5017CF27E
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_RotateRootBone_D6E8C6014B5076050F4A5CA5017CF27E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_RotateRootBone_D6E8C6014B5076050F4A5CA5017CF27E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_RotationOffsetBlendSpace_6A4FA3224D3918675836B8B1F28D4696
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_RotationOffsetBlendSpace_6A4FA3224D3918675836B8B1F28D4696()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_RotationOffsetBlendSpace_6A4FA3224D3918675836B8B1F28D4696");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_54FC781946DD3B60A71A1D85690F3B5C
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_54FC781946DD3B60A71A1D85690F3B5C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_54FC781946DD3B60A71A1D85690F3B5C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_70577A2B4F23E326F38256AA3059FA08
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_70577A2B4F23E326F38256AA3059FA08()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_70577A2B4F23E326F38256AA3059FA08");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_83BDB06A4D4A59D740FF44AD184969E1
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_83BDB06A4D4A59D740FF44AD184969E1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_SequenceEvaluator_83BDB06A4D4A59D740FF44AD184969E1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_0306BC29454C12C0CD5E2FB6A4AD75D1
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_0306BC29454C12C0CD5E2FB6A4AD75D1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_0306BC29454C12C0CD5E2FB6A4AD75D1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_116890C24247DC2ECE5A25BAE724CFED
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_116890C24247DC2ECE5A25BAE724CFED()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_116890C24247DC2ECE5A25BAE724CFED");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_3040462C4AD8925B9D62988893D02A28
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_3040462C4AD8925B9D62988893D02A28()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_3040462C4AD8925B9D62988893D02A28");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_5DED3E3B404CBD74DE3AA5ABFD2D7C0D
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_5DED3E3B404CBD74DE3AA5ABFD2D7C0D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_5DED3E3B404CBD74DE3AA5ABFD2D7C0D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_6FC5B2C549890EF1DADC4AAFD73475F9
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_6FC5B2C549890EF1DADC4AAFD73475F9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_6FC5B2C549890EF1DADC4AAFD73475F9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_BC9FDC764E9892C5523048ACF777BEF0
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_BC9FDC764E9892C5523048ACF777BEF0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_BC9FDC764E9892C5523048ACF777BEF0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_BFD1B9F84DF89CBC24B423B7E7447CFB
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_BFD1B9F84DF89CBC24B423B7E7447CFB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_BFD1B9F84DF89CBC24B423B7E7447CFB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_D7901A5E49877D0BCD53178BA6007B06
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_D7901A5E49877D0BCD53178BA6007B06()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_D7901A5E49877D0BCD53178BA6007B06");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_E710570F4D28B9C4815F5982636D239E
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_E710570F4D28B9C4815F5982636D239E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_E710570F4D28B9C4815F5982636D239E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_ED88E0A940ED450628DB388B695097D5
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_ED88E0A940ED450628DB388B695097D5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_ED88E0A940ED450628DB388B695097D5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GreenBuff_AnimBP.GreenBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_F217A0454CE57AAFE1CE61B78224FC03
// (BlueprintEvent)

void UGreenBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_F217A0454CE57AAFE1CE61B78224FC03()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GreenBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GreenBuff_AnimBP_AnimGraphNode_TransitionResult_F217A0454CE57AAFE1CE61B78224FC03");

	UObject::ProcessEvent(Func, nullptr);
}

}

