#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandardImmunityDamage

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StandardImmunityDamage.StandardImmunityDamage_C
// 0x0000 (0x0670 - 0x0670)
class UStandardImmunityDamage_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StandardImmunityDamage_C">();
	}
	static class UStandardImmunityDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandardImmunityDamage_C>();
	}
};
static_assert(alignof(UStandardImmunityDamage_C) == 0x000010, "Wrong alignment on UStandardImmunityDamage_C");
static_assert(sizeof(UStandardImmunityDamage_C) == 0x000670, "Wrong size on UStandardImmunityDamage_C");

}

