#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VisionManager

#include "Basic.hpp"

#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VisionManager.VisionManager_C
// 0x0010 (0x4A2E0 - 0x4A2D0)
class AVisionManager_C final : public AOrionVisionManager2
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x4A2D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VisionManager_C">();
	}
	static class AVisionManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVisionManager_C>();
	}
};
static_assert(alignof(AVisionManager_C) == 0x000010, "Wrong alignment on AVisionManager_C");
static_assert(sizeof(AVisionManager_C) == 0x04A2E0, "Wrong size on AVisionManager_C");
static_assert(offsetof(AVisionManager_C, DefaultSceneRoot) == 0x04A2D0, "Member 'AVisionManager_C::DefaultSceneRoot' has a wrong offset!");

}

