#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_PedSparrow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_PedSparrow.AnimBP_PedSparrow_C
// 0xBB40 (0xBF70 - 0x0430)
class UAnimBP_PedSparrow_C final : public UOrionHeroPedestalAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_559843054B77CB772D732594B2816051; // 0x0438(0x0048)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_C27B8CAB47615B228E17EC8D6F0F0887; // 0x0480(0x0048)()
	uint8                                         Pad_4C8[0x8];                                      // 0x04C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_TwoBoneIK                    AnimGraphNode_TwoBoneIK_26CECE34412E5C978BA47DBB117DDDFF; // 0x04D0(0x01C0)()
	struct FAnimNode_TwoBoneIK                    AnimGraphNode_TwoBoneIK_A6A5529D43E36538E452D5956F02BA24; // 0x0690(0x01C0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_284187DE49B20A1E7FEDD4A6B5B27D2D; // 0x0850(0x0048)()
	uint8                                         Pad_898[0x8];                                      // 0x0898(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_LookAt                       AnimGraphNode_LookAt_AF6073D845887282E42F6F984C9B4D59; // 0x08A0(0x01A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6FEE96114DFF63E45B26F7A189C46196; // 0x0A40(0x0080)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_A220C1BB455A9B31E0150C9BA4EA83C9; // 0x0AC0(0x0080)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_CA99D8C145FD1A46C4A239A82E0A842C; // 0x0B40(0x0080)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_EDF1B9D04E2DF2C57C91E697705028E2; // 0x0BC0(0x0080)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20064EC5473E1FC840FAAE991D399145; // 0x0C40(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3A21996F460131F80C7D5C8DA1A1AFA1; // 0x0CC0(0x0070)()
	struct FAnimNode_Root                         AnimGraphNode_StateResult_524757C84E5884A9AD06EBB4B30F34CB; // 0x0D30(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2BC0405B4322261E025F87B232E9E72A; // 0x0D78(0x0070)()
	struct FAnimNode_Root                         AnimGraphNode_StateResult_E38F5F634EC91051FEAF94AF3EEA7156; // 0x0DE8(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31E76A544431C2D3E3EC6C910BC42128; // 0x0E30(0x0070)()
	struct FAnimNode_Root                         AnimGraphNode_StateResult_58BD7A34497D8BD7A330B5A320BD12C8; // 0x0EA0(0x0048)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_28506F06401C9D4C9D6B158863D4F17A; // 0x0EE8(0x00D8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1E407F834FA4E4B03F00418E03BA2260; // 0x0FC0(0x0068)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_F93BA97A45BF844EC744749D7724F307; // 0x1028(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_D6151A3048211C46A285B585B71A5EE6; // 0x12A8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_10CBD136499ACE7424757B949931C5C3; // 0x1528(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_4F95631C4088BED74062C4A724D3CE51; // 0x17A8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_BB5836DA41DB6F3AE2C9F5BE0A55A871; // 0x1A28(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_9ED3391F4AE092260F683AB8877BA6B8; // 0x1CA8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_463C0D564F7BC39BA26F069139DEAF88; // 0x1F28(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_829DB66A498A73070019C5BA2017CE8C; // 0x21A8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_46A7F8874DA1620AE4FB278DA81325D8; // 0x2428(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_C8B3782D47303C8579E3AAB2C2A98E3F; // 0x26A8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_302AC2474117D3E48644A9BF7816C4EA; // 0x2928(0x0280)()
	struct FAnimNode_BoneDrivenController         AnimGraphNode_BoneDrivenController_A07A6604420FF89C4152BEAE9BFE727A; // 0x2BA8(0x00E8)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_8433E1C84A634EA19D515FB49D9DB67B; // 0x2C90(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_9C9F68224823476F4D17A8BF748941EF; // 0x2F10(0x0280)()
	struct FAnimNode_BoneDrivenController         AnimGraphNode_BoneDrivenController_0DA6192D494E06E956432B9967C01FE2; // 0x3190(0x00E8)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_E328490C4DE2E20F45CB3B846392099B; // 0x3278(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_41A71CE74E97471CEA84E5A676796A54; // 0x34F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_5E3D930043D1995139870DBB6EB54E54; // 0x3778(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_C00AEC4B478C9DC6AC39F0B991DA941A; // 0x39F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_BF6C385A4C20A1E663C51694343D8D30; // 0x3C78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_D6D8A41B43CFC00DFD5DD49576F2CB01; // 0x3EF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_80FF032147BE6EE37A47A6B4651CB9C9; // 0x4178(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_1B13C32A448611A8D0D501A6E5D7DA30; // 0x43F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_FA12C1C14A9B75A34BB60A8640E80E7B; // 0x4678(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_E4A920D249928C608977E49453B443C3; // 0x48F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_FA0F2AE348A9B8945B5C2081B9A06942; // 0x4B78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_8B3834964633B1B745F992AC6B83F22E; // 0x4DF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_47C57F4C4677FE3422B978A440941A20; // 0x5078(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_A32F420D45694B375E43B8AB2503DC45; // 0x52F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_37FC922C4411CDC4C367FAB94C557342; // 0x5578(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_38F4BE6E42BD83DC6D49BF86F76679FB; // 0x57F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_786BF2654C34BAD7493525807AF19252; // 0x5A78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_C72BE7484A998ECF2055B8A7D1CB8324; // 0x5CF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_0122264E4501E4D343ED28ABD249DDAC; // 0x5F78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_5BDAB1C64C4ACEBE054E62AAF54F5A0D; // 0x61F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_24D011C04414BEB8077582884720D1B9; // 0x6478(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_A6BA410D49B71F85E79BCFA0C599DE2E; // 0x66F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_5CF05FBF4CBC442CB1C521B3827A7973; // 0x6978(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_2A35C61440E716BC6D2112BB10782566; // 0x6BF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_58D5FE004D35496B21A84C9536B212E4; // 0x6E78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_5A2E279B4E5B134D7065229F96B2C067; // 0x70F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_1BE4194A4C96F662281D008BB44A4AF8; // 0x7378(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_16A61121416C7305391C3097FB752ED8; // 0x75F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_CC48E35B44F28141E092EFACE24D0AFF; // 0x7878(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_0B76516A4BA7652F9CE745BD450EC5C4; // 0x7AF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_2050D0CD476A073F25E5F382F3F721AC; // 0x7D78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_4454A2924BA4757ADE55239A0D082674; // 0x7FF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_B2A040AA46E142AA3675AE81D27863AA; // 0x8278(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_8899CC8B418282D5C797918F4809B337; // 0x84F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_5F58C34545E864844B8B33AFF049C07F; // 0x8778(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_D6F2542F4D8B30F2B2D7829A597E0CF7; // 0x89F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_3580933B49A1732ED67A1C92433F1B00; // 0x8C78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_DE29C31B49F7A7972998A3A0867685D6; // 0x8EF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_62ED1FDF4CD0935EB55C4EACCA804F4D; // 0x9178(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_423BCF9941B0554CBC5D3EB82BAFFBE0; // 0x93F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_6C29BF3C42C133931C25259EDBEEC98E; // 0x9678(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_163A83DD432CD9CA36342287FD0E0C16; // 0x98F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_251246134CB912F02118DB8AD4C5839D; // 0x9B78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_505836A74524065BD5EF8D9CB0A51DC0; // 0x9DF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_063CA363477A9944737B0C8BCB1AE869; // 0xA078(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_E8D7875A44015A4BAD8D8391EDE7743D; // 0xA2F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_046096134C563095386B9AA327D1777E; // 0xA578(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_449E4C6941E4D8FF57874886BCDB6EC5; // 0xA7F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_2A13A51542B5F029294B8BB06A2A96F4; // 0xAA78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_2C26E84644AF3FA8805BE791AD55C7B9; // 0xACF8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_B53389284E2CF34CDCFD7DA0BDBFBCBE; // 0xAF78(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_B8EC1DE2463D4BF06E6D3C80016A07C1; // 0xB1F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_18867BBA4249F04961A387B30317462E; // 0xB478(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_646BA905444E692824D55B97D60FE76D; // 0xB6F8(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_D9093D4D46128A023410A5AC189055B6; // 0xB978(0x0280)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics_6C686F3743A492AF166ED6A09568B0D1; // 0xBBF8(0x0280)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_5BE6D1F8429D0530545D73904E28FB24; // 0xBE78(0x0078)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_FF7C219341FAE07D817A74AA9415191B; // 0xBEF0(0x0070)()
	float                                         Arrow_LookAt_BP;                                   // 0xBF60(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AnimBP_PedSparrow(int32 EntryPoint);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_PedSparrow_AnimGraphNode_AnimDynamics_2A13A51542B5F029294B8BB06A2A96F4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_PedSparrow_AnimGraphNode_AnimDynamics_E328490C4DE2E20F45CB3B846392099B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_PedSparrow_AnimGraphNode_TransitionResult_A220C1BB455A9B31E0150C9BA4EA83C9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_PedSparrow_AnimGraphNode_TransitionResult_EDF1B9D04E2DF2C57C91E697705028E2();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_PedSparrow_AnimGraphNode_TwoWayBlend_5BE6D1F8429D0530545D73904E28FB24();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBP_PedSparrow_C">();
	}
	static class UAnimBP_PedSparrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_PedSparrow_C>();
	}
};
static_assert(alignof(UAnimBP_PedSparrow_C) == 0x000010, "Wrong alignment on UAnimBP_PedSparrow_C");
static_assert(sizeof(UAnimBP_PedSparrow_C) == 0x00BF70, "Wrong size on UAnimBP_PedSparrow_C");
static_assert(offsetof(UAnimBP_PedSparrow_C, UberGraphFrame) == 0x000430, "Member 'UAnimBP_PedSparrow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_Root_559843054B77CB772D732594B2816051) == 0x000438, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_Root_559843054B77CB772D732594B2816051' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_LocalToComponentSpace_C27B8CAB47615B228E17EC8D6F0F0887) == 0x000480, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_LocalToComponentSpace_C27B8CAB47615B228E17EC8D6F0F0887' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TwoBoneIK_26CECE34412E5C978BA47DBB117DDDFF) == 0x0004D0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TwoBoneIK_26CECE34412E5C978BA47DBB117DDDFF' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TwoBoneIK_A6A5529D43E36538E452D5956F02BA24) == 0x000690, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TwoBoneIK_A6A5529D43E36538E452D5956F02BA24' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_ComponentToLocalSpace_284187DE49B20A1E7FEDD4A6B5B27D2D) == 0x000850, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_ComponentToLocalSpace_284187DE49B20A1E7FEDD4A6B5B27D2D' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_LookAt_AF6073D845887282E42F6F984C9B4D59) == 0x0008A0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_LookAt_AF6073D845887282E42F6F984C9B4D59' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TransitionResult_6FEE96114DFF63E45B26F7A189C46196) == 0x000A40, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TransitionResult_6FEE96114DFF63E45B26F7A189C46196' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TransitionResult_A220C1BB455A9B31E0150C9BA4EA83C9) == 0x000AC0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TransitionResult_A220C1BB455A9B31E0150C9BA4EA83C9' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TransitionResult_CA99D8C145FD1A46C4A239A82E0A842C) == 0x000B40, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TransitionResult_CA99D8C145FD1A46C4A239A82E0A842C' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TransitionResult_EDF1B9D04E2DF2C57C91E697705028E2) == 0x000BC0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TransitionResult_EDF1B9D04E2DF2C57C91E697705028E2' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TransitionResult_20064EC5473E1FC840FAAE991D399145) == 0x000C40, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TransitionResult_20064EC5473E1FC840FAAE991D399145' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_SequencePlayer_3A21996F460131F80C7D5C8DA1A1AFA1) == 0x000CC0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_SequencePlayer_3A21996F460131F80C7D5C8DA1A1AFA1' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_StateResult_524757C84E5884A9AD06EBB4B30F34CB) == 0x000D30, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_StateResult_524757C84E5884A9AD06EBB4B30F34CB' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_SequencePlayer_2BC0405B4322261E025F87B232E9E72A) == 0x000D78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_SequencePlayer_2BC0405B4322261E025F87B232E9E72A' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_StateResult_E38F5F634EC91051FEAF94AF3EEA7156) == 0x000DE8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_StateResult_E38F5F634EC91051FEAF94AF3EEA7156' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_SequencePlayer_31E76A544431C2D3E3EC6C910BC42128) == 0x000E30, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_SequencePlayer_31E76A544431C2D3E3EC6C910BC42128' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_StateResult_58BD7A34497D8BD7A330B5A320BD12C8) == 0x000EA0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_StateResult_58BD7A34497D8BD7A330B5A320BD12C8' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_StateMachine_28506F06401C9D4C9D6B158863D4F17A) == 0x000EE8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_StateMachine_28506F06401C9D4C9D6B158863D4F17A' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_Slot_1E407F834FA4E4B03F00418E03BA2260) == 0x000FC0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_Slot_1E407F834FA4E4B03F00418E03BA2260' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_F93BA97A45BF844EC744749D7724F307) == 0x001028, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_F93BA97A45BF844EC744749D7724F307' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_D6151A3048211C46A285B585B71A5EE6) == 0x0012A8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_D6151A3048211C46A285B585B71A5EE6' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_10CBD136499ACE7424757B949931C5C3) == 0x001528, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_10CBD136499ACE7424757B949931C5C3' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_4F95631C4088BED74062C4A724D3CE51) == 0x0017A8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_4F95631C4088BED74062C4A724D3CE51' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_BB5836DA41DB6F3AE2C9F5BE0A55A871) == 0x001A28, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_BB5836DA41DB6F3AE2C9F5BE0A55A871' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_9ED3391F4AE092260F683AB8877BA6B8) == 0x001CA8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_9ED3391F4AE092260F683AB8877BA6B8' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_463C0D564F7BC39BA26F069139DEAF88) == 0x001F28, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_463C0D564F7BC39BA26F069139DEAF88' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_829DB66A498A73070019C5BA2017CE8C) == 0x0021A8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_829DB66A498A73070019C5BA2017CE8C' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_46A7F8874DA1620AE4FB278DA81325D8) == 0x002428, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_46A7F8874DA1620AE4FB278DA81325D8' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_C8B3782D47303C8579E3AAB2C2A98E3F) == 0x0026A8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_C8B3782D47303C8579E3AAB2C2A98E3F' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_302AC2474117D3E48644A9BF7816C4EA) == 0x002928, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_302AC2474117D3E48644A9BF7816C4EA' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_BoneDrivenController_A07A6604420FF89C4152BEAE9BFE727A) == 0x002BA8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_BoneDrivenController_A07A6604420FF89C4152BEAE9BFE727A' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_8433E1C84A634EA19D515FB49D9DB67B) == 0x002C90, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_8433E1C84A634EA19D515FB49D9DB67B' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_9C9F68224823476F4D17A8BF748941EF) == 0x002F10, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_9C9F68224823476F4D17A8BF748941EF' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_BoneDrivenController_0DA6192D494E06E956432B9967C01FE2) == 0x003190, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_BoneDrivenController_0DA6192D494E06E956432B9967C01FE2' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_E328490C4DE2E20F45CB3B846392099B) == 0x003278, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_E328490C4DE2E20F45CB3B846392099B' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_41A71CE74E97471CEA84E5A676796A54) == 0x0034F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_41A71CE74E97471CEA84E5A676796A54' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_5E3D930043D1995139870DBB6EB54E54) == 0x003778, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_5E3D930043D1995139870DBB6EB54E54' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_C00AEC4B478C9DC6AC39F0B991DA941A) == 0x0039F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_C00AEC4B478C9DC6AC39F0B991DA941A' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_BF6C385A4C20A1E663C51694343D8D30) == 0x003C78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_BF6C385A4C20A1E663C51694343D8D30' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_D6D8A41B43CFC00DFD5DD49576F2CB01) == 0x003EF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_D6D8A41B43CFC00DFD5DD49576F2CB01' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_80FF032147BE6EE37A47A6B4651CB9C9) == 0x004178, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_80FF032147BE6EE37A47A6B4651CB9C9' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_1B13C32A448611A8D0D501A6E5D7DA30) == 0x0043F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_1B13C32A448611A8D0D501A6E5D7DA30' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_FA12C1C14A9B75A34BB60A8640E80E7B) == 0x004678, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_FA12C1C14A9B75A34BB60A8640E80E7B' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_E4A920D249928C608977E49453B443C3) == 0x0048F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_E4A920D249928C608977E49453B443C3' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_FA0F2AE348A9B8945B5C2081B9A06942) == 0x004B78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_FA0F2AE348A9B8945B5C2081B9A06942' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_8B3834964633B1B745F992AC6B83F22E) == 0x004DF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_8B3834964633B1B745F992AC6B83F22E' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_47C57F4C4677FE3422B978A440941A20) == 0x005078, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_47C57F4C4677FE3422B978A440941A20' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_A32F420D45694B375E43B8AB2503DC45) == 0x0052F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_A32F420D45694B375E43B8AB2503DC45' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_37FC922C4411CDC4C367FAB94C557342) == 0x005578, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_37FC922C4411CDC4C367FAB94C557342' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_38F4BE6E42BD83DC6D49BF86F76679FB) == 0x0057F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_38F4BE6E42BD83DC6D49BF86F76679FB' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_786BF2654C34BAD7493525807AF19252) == 0x005A78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_786BF2654C34BAD7493525807AF19252' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_C72BE7484A998ECF2055B8A7D1CB8324) == 0x005CF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_C72BE7484A998ECF2055B8A7D1CB8324' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_0122264E4501E4D343ED28ABD249DDAC) == 0x005F78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_0122264E4501E4D343ED28ABD249DDAC' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_5BDAB1C64C4ACEBE054E62AAF54F5A0D) == 0x0061F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_5BDAB1C64C4ACEBE054E62AAF54F5A0D' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_24D011C04414BEB8077582884720D1B9) == 0x006478, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_24D011C04414BEB8077582884720D1B9' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_A6BA410D49B71F85E79BCFA0C599DE2E) == 0x0066F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_A6BA410D49B71F85E79BCFA0C599DE2E' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_5CF05FBF4CBC442CB1C521B3827A7973) == 0x006978, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_5CF05FBF4CBC442CB1C521B3827A7973' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_2A35C61440E716BC6D2112BB10782566) == 0x006BF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_2A35C61440E716BC6D2112BB10782566' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_58D5FE004D35496B21A84C9536B212E4) == 0x006E78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_58D5FE004D35496B21A84C9536B212E4' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_5A2E279B4E5B134D7065229F96B2C067) == 0x0070F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_5A2E279B4E5B134D7065229F96B2C067' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_1BE4194A4C96F662281D008BB44A4AF8) == 0x007378, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_1BE4194A4C96F662281D008BB44A4AF8' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_16A61121416C7305391C3097FB752ED8) == 0x0075F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_16A61121416C7305391C3097FB752ED8' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_CC48E35B44F28141E092EFACE24D0AFF) == 0x007878, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_CC48E35B44F28141E092EFACE24D0AFF' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_0B76516A4BA7652F9CE745BD450EC5C4) == 0x007AF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_0B76516A4BA7652F9CE745BD450EC5C4' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_2050D0CD476A073F25E5F382F3F721AC) == 0x007D78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_2050D0CD476A073F25E5F382F3F721AC' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_4454A2924BA4757ADE55239A0D082674) == 0x007FF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_4454A2924BA4757ADE55239A0D082674' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_B2A040AA46E142AA3675AE81D27863AA) == 0x008278, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_B2A040AA46E142AA3675AE81D27863AA' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_8899CC8B418282D5C797918F4809B337) == 0x0084F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_8899CC8B418282D5C797918F4809B337' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_5F58C34545E864844B8B33AFF049C07F) == 0x008778, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_5F58C34545E864844B8B33AFF049C07F' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_D6F2542F4D8B30F2B2D7829A597E0CF7) == 0x0089F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_D6F2542F4D8B30F2B2D7829A597E0CF7' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_3580933B49A1732ED67A1C92433F1B00) == 0x008C78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_3580933B49A1732ED67A1C92433F1B00' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_DE29C31B49F7A7972998A3A0867685D6) == 0x008EF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_DE29C31B49F7A7972998A3A0867685D6' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_62ED1FDF4CD0935EB55C4EACCA804F4D) == 0x009178, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_62ED1FDF4CD0935EB55C4EACCA804F4D' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_423BCF9941B0554CBC5D3EB82BAFFBE0) == 0x0093F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_423BCF9941B0554CBC5D3EB82BAFFBE0' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_6C29BF3C42C133931C25259EDBEEC98E) == 0x009678, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_6C29BF3C42C133931C25259EDBEEC98E' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_163A83DD432CD9CA36342287FD0E0C16) == 0x0098F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_163A83DD432CD9CA36342287FD0E0C16' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_251246134CB912F02118DB8AD4C5839D) == 0x009B78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_251246134CB912F02118DB8AD4C5839D' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_505836A74524065BD5EF8D9CB0A51DC0) == 0x009DF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_505836A74524065BD5EF8D9CB0A51DC0' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_063CA363477A9944737B0C8BCB1AE869) == 0x00A078, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_063CA363477A9944737B0C8BCB1AE869' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_E8D7875A44015A4BAD8D8391EDE7743D) == 0x00A2F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_E8D7875A44015A4BAD8D8391EDE7743D' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_046096134C563095386B9AA327D1777E) == 0x00A578, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_046096134C563095386B9AA327D1777E' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_449E4C6941E4D8FF57874886BCDB6EC5) == 0x00A7F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_449E4C6941E4D8FF57874886BCDB6EC5' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_2A13A51542B5F029294B8BB06A2A96F4) == 0x00AA78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_2A13A51542B5F029294B8BB06A2A96F4' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_2C26E84644AF3FA8805BE791AD55C7B9) == 0x00ACF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_2C26E84644AF3FA8805BE791AD55C7B9' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_B53389284E2CF34CDCFD7DA0BDBFBCBE) == 0x00AF78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_B53389284E2CF34CDCFD7DA0BDBFBCBE' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_B8EC1DE2463D4BF06E6D3C80016A07C1) == 0x00B1F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_B8EC1DE2463D4BF06E6D3C80016A07C1' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_18867BBA4249F04961A387B30317462E) == 0x00B478, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_18867BBA4249F04961A387B30317462E' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_646BA905444E692824D55B97D60FE76D) == 0x00B6F8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_646BA905444E692824D55B97D60FE76D' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_D9093D4D46128A023410A5AC189055B6) == 0x00B978, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_D9093D4D46128A023410A5AC189055B6' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_AnimDynamics_6C686F3743A492AF166ED6A09568B0D1) == 0x00BBF8, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_AnimDynamics_6C686F3743A492AF166ED6A09568B0D1' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_TwoWayBlend_5BE6D1F8429D0530545D73904E28FB24) == 0x00BE78, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_TwoWayBlend_5BE6D1F8429D0530545D73904E28FB24' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, AnimGraphNode_SequencePlayer_FF7C219341FAE07D817A74AA9415191B) == 0x00BEF0, "Member 'UAnimBP_PedSparrow_C::AnimGraphNode_SequencePlayer_FF7C219341FAE07D817A74AA9415191B' has a wrong offset!");
static_assert(offsetof(UAnimBP_PedSparrow_C, Arrow_LookAt_BP) == 0x00BF60, "Member 'UAnimBP_PedSparrow_C::Arrow_LookAt_BP' has a wrong offset!");

}

