#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraLens_Blind_Apply

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CameraLens_Blind_Apply.BP_CameraLens_Blind_Apply_C.UserConstructionScript
// 0x0010 (0x0010 - 0x0000)
struct BP_CameraLens_Blind_Apply_C_UserConstructionScript final
{
public:
	class AExponentialHeightFog*                  CallFunc_GetGlobalExponentialHeightFog_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CameraLens_Blind_Apply_C_UserConstructionScript) == 0x000008, "Wrong alignment on BP_CameraLens_Blind_Apply_C_UserConstructionScript");
static_assert(sizeof(BP_CameraLens_Blind_Apply_C_UserConstructionScript) == 0x000010, "Wrong size on BP_CameraLens_Blind_Apply_C_UserConstructionScript");
static_assert(offsetof(BP_CameraLens_Blind_Apply_C_UserConstructionScript, CallFunc_GetGlobalExponentialHeightFog_ReturnValue) == 0x000000, "Member 'BP_CameraLens_Blind_Apply_C_UserConstructionScript::CallFunc_GetGlobalExponentialHeightFog_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CameraLens_Blind_Apply_C_UserConstructionScript, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_CameraLens_Blind_Apply_C_UserConstructionScript::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

