#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Card_AbilityMimic

#include "Basic.hpp"

#include "GA_Card_AbilityMimic_classes.hpp"
#include "GA_Card_AbilityMimic_parameters.hpp"


namespace SDK
{

// Function GA_Card_AbilityMimic.GA_Card_AbilityMimic_C.ExecuteUbergraph_GA_Card_AbilityMimic
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Card_AbilityMimic_C::ExecuteUbergraph_GA_Card_AbilityMimic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_AbilityMimic_C", "ExecuteUbergraph_GA_Card_AbilityMimic");

	Params::GA_Card_AbilityMimic_C_ExecuteUbergraph_GA_Card_AbilityMimic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Card_AbilityMimic.GA_Card_AbilityMimic_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Card_AbilityMimic_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_AbilityMimic_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

