#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Card_Metamorphosis_Target

#include "Basic.hpp"

#include "GA_Card_Metamorphosis_Target_classes.hpp"
#include "GA_Card_Metamorphosis_Target_parameters.hpp"


namespace SDK
{

// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.ExecuteUbergraph_GA_Card_Metamorphosis_Target
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Card_Metamorphosis_Target_C::ExecuteUbergraph_GA_Card_Metamorphosis_Target(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "ExecuteUbergraph_GA_Card_Metamorphosis_Target");

	Params::GA_Card_Metamorphosis_Target_C_ExecuteUbergraph_GA_Card_Metamorphosis_Target Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.Removed_B353AE03499D7BBEA8396F8F8E6799EA
// (BlueprintCallable, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::Removed_B353AE03499D7BBEA8396F8F8E6799EA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "Removed_B353AE03499D7BBEA8396F8F8E6799EA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.Added_490568ED49A7056A9E95DEA14EE2095C
// (BlueprintCallable, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::Added_490568ED49A7056A9E95DEA14EE2095C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "Added_490568ED49A7056A9E95DEA14EE2095C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.Removed_7873B7944785CE839F9214AC7B7D603E
// (BlueprintCallable, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::Removed_7873B7944785CE839F9214AC7B7D603E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "Removed_7873B7944785CE839F9214AC7B7D603E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.Added_C2C116DC4045151F4D8F8497C0063F1D
// (BlueprintCallable, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::Added_C2C116DC4045151F4D8F8497C0063F1D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "Added_C2C116DC4045151F4D8F8497C0063F1D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.OnStateEnded_795D206F435D4A4A5D699B9A483F6861
// (BlueprintCallable, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::OnStateEnded_795D206F435D4A4A5D699B9A483F6861()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "OnStateEnded_795D206F435D4A4A5D699B9A483F6861");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.OnStateInterrupted_795D206F435D4A4A5D699B9A483F6861
// (BlueprintCallable, BlueprintEvent)

void UGA_Card_Metamorphosis_Target_C::OnStateInterrupted_795D206F435D4A4A5D699B9A483F6861()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "OnStateInterrupted_795D206F435D4A4A5D699B9A483F6861");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.Success_5578B286496AE0E55E901A8B4327D2CF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SpawnedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Card_Metamorphosis_Target_C::Success_5578B286496AE0E55E901A8B4327D2CF(class AActor* SpawnedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "Success_5578B286496AE0E55E901A8B4327D2CF");

	Params::GA_Card_Metamorphosis_Target_C_Success_5578B286496AE0E55E901A8B4327D2CF Parms{};

	Parms.SpawnedActor = SpawnedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.NotAuthority_5578B286496AE0E55E901A8B4327D2CF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SpawnedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Card_Metamorphosis_Target_C::NotAuthority_5578B286496AE0E55E901A8B4327D2CF(class AActor* SpawnedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "NotAuthority_5578B286496AE0E55E901A8B4327D2CF");

	Params::GA_Card_Metamorphosis_Target_C_NotAuthority_5578B286496AE0E55E901A8B4327D2CF Parms{};

	Parms.SpawnedActor = SpawnedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.FailedToSpawn_5578B286496AE0E55E901A8B4327D2CF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SpawnedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Card_Metamorphosis_Target_C::FailedToSpawn_5578B286496AE0E55E901A8B4327D2CF(class AActor* SpawnedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "FailedToSpawn_5578B286496AE0E55E901A8B4327D2CF");

	Params::GA_Card_Metamorphosis_Target_C_FailedToSpawn_5578B286496AE0E55E901A8B4327D2CF Parms{};

	Parms.SpawnedActor = SpawnedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Card_Metamorphosis_Target.GA_Card_Metamorphosis_Target_C.K2_CanActivateAbility
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
// struct FGameplayTagContainer            RelevantTags                                           (Parm, OutParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGA_Card_Metamorphosis_Target_C::K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, struct FGameplayTagContainer* RelevantTags) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Metamorphosis_Target_C", "K2_CanActivateAbility");

	Params::GA_Card_Metamorphosis_Target_C_K2_CanActivateAbility Parms{};

	Parms.ActorInfo = std::move(ActorInfo);

	UObject::ProcessEvent(Func, &Parms);

	if (RelevantTags != nullptr)
		*RelevantTags = std::move(Parms.RelevantTags);

	return Parms.ReturnValue;
}

}

