#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Card_Aura_HealingAura

#include "Basic.hpp"

#include "GA_Card_Aura_HealingAura_classes.hpp"
#include "GA_Card_Aura_HealingAura_parameters.hpp"


namespace SDK
{

// Function GA_Card_Aura_HealingAura.GA_Card_Aura_HealingAura_C.ExecuteUbergraph_GA_Card_Aura_HealingAura
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Card_Aura_HealingAura_C::ExecuteUbergraph_GA_Card_Aura_HealingAura(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Aura_HealingAura_C", "ExecuteUbergraph_GA_Card_Aura_HealingAura");

	Params::GA_Card_Aura_HealingAura_C_ExecuteUbergraph_GA_Card_Aura_HealingAura Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Card_Aura_HealingAura.GA_Card_Aura_HealingAura_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Card_Aura_HealingAura_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Card_Aura_HealingAura_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

