#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Dragon_Spawn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Dragon_Spawn.GA_Dragon_Spawn_C
// 0x0010 (0x0B80 - 0x0B70)
class UGA_Dragon_Spawn_C final : public UOrionAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B70(0x0008)(Transient, DuplicateTransient)
	class UAnimMontage*                           SpawnAnim;                                         // 0x0B78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Dragon_Spawn(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnBlendOut_2151C45A4C87C66D1242328DCC0D6B33(class FName NotifyName);
	void OnCancelled_2151C45A4C87C66D1242328DCC0D6B33(class FName NotifyName);
	void OnCompleted_2151C45A4C87C66D1242328DCC0D6B33(class FName NotifyName);
	void OnFinish_69B4A7B44052116A809DAE85D43FE597();
	void OnInterrupted_2151C45A4C87C66D1242328DCC0D6B33(class FName NotifyName);
	void OnNotifyBegin_2151C45A4C87C66D1242328DCC0D6B33(class FName NotifyName);
	void OnNotifyEnd_2151C45A4C87C66D1242328DCC0D6B33(class FName NotifyName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Dragon_Spawn_C">();
	}
	static class UGA_Dragon_Spawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Dragon_Spawn_C>();
	}
};
static_assert(alignof(UGA_Dragon_Spawn_C) == 0x000010, "Wrong alignment on UGA_Dragon_Spawn_C");
static_assert(sizeof(UGA_Dragon_Spawn_C) == 0x000B80, "Wrong size on UGA_Dragon_Spawn_C");
static_assert(offsetof(UGA_Dragon_Spawn_C, UberGraphFrame) == 0x000B70, "Member 'UGA_Dragon_Spawn_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGA_Dragon_Spawn_C, SpawnAnim) == 0x000B78, "Member 'UGA_Dragon_Spawn_C::SpawnAnim' has a wrong offset!");

}

