#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Core_Under_Attack_VO

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Core_Under_Attack_VO.GE_Core_Under_Attack_VO_C
// 0x0000 (0x0670 - 0x0670)
class UGE_Core_Under_Attack_VO_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Core_Under_Attack_VO_C">();
	}
	static class UGE_Core_Under_Attack_VO_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Core_Under_Attack_VO_C>();
	}
};
static_assert(alignof(UGE_Core_Under_Attack_VO_C) == 0x000010, "Wrong alignment on UGE_Core_Under_Attack_VO_C");
static_assert(sizeof(UGE_Core_Under_Attack_VO_C) == 0x000670, "Wrong size on UGE_Core_Under_Attack_VO_C");

}

