#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GoldBuff_AnimBP

#include "Basic.hpp"

#include "GoldBuff_AnimBP_classes.hpp"
#include "GoldBuff_AnimBP_parameters.hpp"


namespace SDK
{

// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.ExecuteUbergraph_GoldBuff_AnimBP
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGoldBuff_AnimBP_C::ExecuteUbergraph_GoldBuff_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "ExecuteUbergraph_GoldBuff_AnimBP");

	Params::GoldBuff_AnimBP_C_ExecuteUbergraph_GoldBuff_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGoldBuff_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "BlueprintUpdateAnimation");

	Params::GoldBuff_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_ApplyAdditive_97919802402F3F719C4C17BA96282362
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_ApplyAdditive_97919802402F3F719C4C17BA96282362()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_ApplyAdditive_97919802402F3F719C4C17BA96282362");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendListByBool_0237C07942B69678C4680D84994F71D3
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendListByBool_0237C07942B69678C4680D84994F71D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendListByBool_0237C07942B69678C4680D84994F71D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendListByBool_BAE422B24A3A36CD8D0041AEEDF2105F
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendListByBool_BAE422B24A3A36CD8D0041AEEDF2105F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendListByBool_BAE422B24A3A36CD8D0041AEEDF2105F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendSpacePlayer_3F9F022C4C5D898C896E78843685FC2F
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendSpacePlayer_3F9F022C4C5D898C896E78843685FC2F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_BlendSpacePlayer_3F9F022C4C5D898C896E78843685FC2F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_RotateRootBone_E827A0884C3187A7A553D8A1A33436DD
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_RotateRootBone_E827A0884C3187A7A553D8A1A33436DD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_RotateRootBone_E827A0884C3187A7A553D8A1A33436DD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_RotationOffsetBlendSpace_6FE2A86D41258BF786D498AA3421500E
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_RotationOffsetBlendSpace_6FE2A86D41258BF786D498AA3421500E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_RotationOffsetBlendSpace_6FE2A86D41258BF786D498AA3421500E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_2930925146F1B4F516FD7E97A797C326
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_2930925146F1B4F516FD7E97A797C326()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_2930925146F1B4F516FD7E97A797C326");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_362780404222F8FD2ABD62965FAC75D2
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_362780404222F8FD2ABD62965FAC75D2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_362780404222F8FD2ABD62965FAC75D2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_FE5C7B5845B4A450816B2588209BFAF4
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_FE5C7B5845B4A450816B2588209BFAF4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_SequenceEvaluator_FE5C7B5845B4A450816B2588209BFAF4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_355E063347F8777599861EA85B0D4684
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_355E063347F8777599861EA85B0D4684()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_355E063347F8777599861EA85B0D4684");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_415F3E3B429A53CD15E612985D62E79B
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_415F3E3B429A53CD15E612985D62E79B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_415F3E3B429A53CD15E612985D62E79B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_7AA4A61448A582CE9A9500A5522F296B
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_7AA4A61448A582CE9A9500A5522F296B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_7AA4A61448A582CE9A9500A5522F296B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_7AD98CB744137F5BE58FAF85E7D09E8B
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_7AD98CB744137F5BE58FAF85E7D09E8B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_7AD98CB744137F5BE58FAF85E7D09E8B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_8F2FE22C46E2BE74397D938212625B91
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_8F2FE22C46E2BE74397D938212625B91()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_8F2FE22C46E2BE74397D938212625B91");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_ABB0759549FED8D154408B94738A7AF2
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_ABB0759549FED8D154408B94738A7AF2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_ABB0759549FED8D154408B94738A7AF2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_B76ED2144DF1902A192DA0B20825782C
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_B76ED2144DF1902A192DA0B20825782C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_B76ED2144DF1902A192DA0B20825782C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_BE5C158F41215E219CA4699A4411D037
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_BE5C158F41215E219CA4699A4411D037()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_BE5C158F41215E219CA4699A4411D037");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_D2B6A84F4C00D3675A4F72B298475320
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_D2B6A84F4C00D3675A4F72B298475320()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_D2B6A84F4C00D3675A4F72B298475320");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_DD35B2014696C75E95E58E8E2CE65305
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_DD35B2014696C75E95E58E8E2CE65305()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_DD35B2014696C75E95E58E8E2CE65305");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GoldBuff_AnimBP.GoldBuff_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_F68D2E044F5F2118D6A0B8A917F05D75
// (BlueprintEvent)

void UGoldBuff_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_F68D2E044F5F2118D6A0B8A917F05D75()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GoldBuff_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_GoldBuff_AnimBP_AnimGraphNode_TransitionResult_F68D2E044F5F2118D6A0B8A917F05D75");

	UObject::ProcessEvent(Func, nullptr);
}

}

