#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandardCriticallyWounded

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StandardCriticallyWounded.StandardCriticallyWounded_C
// 0x0000 (0x0670 - 0x0670)
class UStandardCriticallyWounded_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StandardCriticallyWounded_C">();
	}
	static class UStandardCriticallyWounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandardCriticallyWounded_C>();
	}
};
static_assert(alignof(UStandardCriticallyWounded_C) == 0x000010, "Wrong alignment on UStandardCriticallyWounded_C");
static_assert(sizeof(UStandardCriticallyWounded_C) == 0x000670, "Wrong size on UStandardCriticallyWounded_C");

}

