#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandardCooldown

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StandardCooldown.StandardCooldown_C
// 0x0000 (0x0670 - 0x0670)
class UStandardCooldown_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StandardCooldown_C">();
	}
	static class UStandardCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandardCooldown_C>();
	}
};
static_assert(alignof(UStandardCooldown_C) == 0x000010, "Wrong alignment on UStandardCooldown_C");
static_assert(sizeof(UStandardCooldown_C) == 0x000670, "Wrong size on UStandardCooldown_C");

}

