#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusKey

#include "Basic.hpp"

#include "TextStyleMinusBody_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Key.TextStyle-Key_C
// 0x0000 (0x0228 - 0x0228)
class UTextStyleMinusKey_C final : public UTextStyleMinusBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Key_C">();
	}
	static class UTextStyleMinusKey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusKey_C>();
	}
};
static_assert(alignof(UTextStyleMinusKey_C) == 0x000008, "Wrong alignment on UTextStyleMinusKey_C");
static_assert(sizeof(UTextStyleMinusKey_C) == 0x000228, "Wrong size on UTextStyleMinusKey_C");

}

