#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AbilityReadyWidget

#include "Basic.hpp"

#include "OrionGame_structs.hpp"


namespace SDK::Params
{

// Function AbilityReadyWidget.AbilityReadyWidget_C.ExecuteUbergraph_AbilityReadyWidget
// 0x01E0 (0x01E0 - 0x0000)
struct AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EOrionAbilityBinding InputID, const struct FOrionAbilityUIData& AbilityData)> K2Node_CreateDelegate_OutputDelegate; // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	EOrionAbilityBinding                          K2Node_CustomEvent_InputID2;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOrionAbilityUIData                    K2Node_CustomEvent_AbilityData2;                   // 0x0020(0x00C0)()
	TDelegate<void(EOrionAbilityBinding InputID, const struct FOrionAbilityUIData& AbilityData)> K2Node_CreateDelegate_OutputDelegate2; // 0x00E0(0x0010)(ZeroConstructor, NoDestructor)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue2;          // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetCurrentMaterialTime_ReturnValue;       // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHUDContext*                            CallFunc_GetContext_ReturnValue;                   // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOrionAbilityBinding                          K2Node_CustomEvent_InputID;                        // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOrionAbilityUIData                    K2Node_CustomEvent_AbilityData;                    // 0x0118(0x00C0)()
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget) == 0x000008, "Wrong alignment on AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget");
static_assert(sizeof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget) == 0x0001E0, "Wrong size on AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, EntryPoint) == 0x000000, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_CustomEvent_InputID2) == 0x000018, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_CustomEvent_InputID2' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_CustomEvent_AbilityData2) == 0x000020, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_CustomEvent_AbilityData2' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_CreateDelegate_OutputDelegate2) == 0x0000E0, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_CreateDelegate_OutputDelegate2' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, CallFunc_GetDynamicMaterial_ReturnValue) == 0x0000F0, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, CallFunc_GetDynamicMaterial_ReturnValue2) == 0x0000F8, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::CallFunc_GetDynamicMaterial_ReturnValue2' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, CallFunc_GetCurrentMaterialTime_ReturnValue) == 0x000100, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::CallFunc_GetCurrentMaterialTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, CallFunc_GetContext_ReturnValue) == 0x000108, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_CustomEvent_InputID) == 0x000110, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_CustomEvent_InputID' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_CustomEvent_AbilityData) == 0x000118, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_CustomEvent_AbilityData' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget, K2Node_SwitchEnum_CmpSuccess) == 0x0001D8, "Member 'AbilityReadyWidget_C_ExecuteUbergraph_AbilityReadyWidget::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function AbilityReadyWidget.AbilityReadyWidget_C.OnAbilityFinishedCooldown_Bind
// 0x00C8 (0x00C8 - 0x0000)
struct AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind final
{
public:
	EOrionAbilityBinding                          InputID;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOrionAbilityUIData                    AbilityData;                                       // 0x0008(0x00C0)(Parm)
};
static_assert(alignof(AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind) == 0x000008, "Wrong alignment on AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind");
static_assert(sizeof(AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind) == 0x0000C8, "Wrong size on AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind");
static_assert(offsetof(AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind, InputID) == 0x000000, "Member 'AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind::InputID' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind, AbilityData) == 0x000008, "Member 'AbilityReadyWidget_C_OnAbilityFinishedCooldown_Bind::AbilityData' has a wrong offset!");

// Function AbilityReadyWidget.AbilityReadyWidget_C.OnAbilityUnlocked_Bind
// 0x00C8 (0x00C8 - 0x0000)
struct AbilityReadyWidget_C_OnAbilityUnlocked_Bind final
{
public:
	EOrionAbilityBinding                          InputID;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOrionAbilityUIData                    AbilityData;                                       // 0x0008(0x00C0)(Parm)
};
static_assert(alignof(AbilityReadyWidget_C_OnAbilityUnlocked_Bind) == 0x000008, "Wrong alignment on AbilityReadyWidget_C_OnAbilityUnlocked_Bind");
static_assert(sizeof(AbilityReadyWidget_C_OnAbilityUnlocked_Bind) == 0x0000C8, "Wrong size on AbilityReadyWidget_C_OnAbilityUnlocked_Bind");
static_assert(offsetof(AbilityReadyWidget_C_OnAbilityUnlocked_Bind, InputID) == 0x000000, "Member 'AbilityReadyWidget_C_OnAbilityUnlocked_Bind::InputID' has a wrong offset!");
static_assert(offsetof(AbilityReadyWidget_C_OnAbilityUnlocked_Bind, AbilityData) == 0x000008, "Member 'AbilityReadyWidget_C_OnAbilityUnlocked_Bind::AbilityData' has a wrong offset!");

}

