#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GSM_MOBA_1v1_Tutorial

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "OrionGame_structs.hpp"
#include "OrionGame_classes.hpp"
#include "AIModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GSM_MOBA_1v1_Tutorial.BP_GSM_MOBA_1v1_Tutorial_C
// 0x02C0 (0x0A20 - 0x0760)
class ABP_GSM_MOBA_1v1_Tutorial_C final : public AOrionGameState_MOBA_Tutorial
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0760(0x0008)(Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AOrionDamageableObjective_Base*         Core_Red;                                          // 0x0770(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class AOrionDamageableObjective_Base*         Inhib_Red;                                         // 0x0778(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class AOrionDamageableObjective_Base*         Tower_Red;                                         // 0x0780(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Core_Seq_Red;                                      // 0x0788(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Inhib_Seq_Red;                                     // 0x0790(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Tower_Seq_Red;                                     // 0x0798(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Core_LookAt_Red;                                   // 0x07A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Inhib_LookAt_Red;                                  // 0x07A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Tower_LookAt_Red;                                  // 0x07B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOrionDamageableObjective_Base*         Core_Blue;                                         // 0x07B8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class AOrionDamageableObjective_Base*         Inhib_Blue;                                        // 0x07C0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class AOrionDamageableObjective_Base*         Tower_Blue;                                        // 0x07C8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Tutorial_FirstSpawn;                               // 0x07D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Welcome_Seq;                                       // 0x07D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_OrionCharAISpawner_C*               AISpawner_Blue;                                    // 0x07E0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class ABP_OrionCharAISpawner_C*               AISpawner_Red;                                     // 0x07E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Minions_LookAt_FirstCombat;                        // 0x07F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    FirstCombat_Seq;                                   // 0x07F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    FirstAbility_Seq;                                  // 0x0800(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UClass*>                         TutorialClasses;                                   // 0x0808(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	class ALevelSequenceActor*                    Pause_Seq;                                         // 0x0818(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Unpause_Seq;                                       // 0x0820(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_WeakenAI_Health;                                // 0x0828(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_LookAt_FirstAbility;                            // 0x0830(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Tower_LookAt_Blue;                                 // 0x0838(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Tower_Seq_Blue;                                    // 0x0840(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Tower_Aggro_Hero;                               // 0x0848(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Tower_Aggro_Minion;                             // 0x0850(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Inhib_LookAt_Blue;                                 // 0x0858(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Core_LookAt_Blue;                                  // 0x0860(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Core_Seq_Blue;                                     // 0x0868(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    Inhib_Seq_Blue;                                    // 0x0870(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Inhib_Aggro_Hero;                               // 0x0878(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Inhib_Aggro_Minion;                             // 0x0880(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Core_Aggro_Hero;                                // 0x0888(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Core_Aggro_Minion;                              // 0x0890(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       tutorial_1v1_tower_destroy;                        // 0x0898(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       tutorial_1v1_inhib_destroy;                        // 0x08A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       tutorial_1v1_core_destroy;                         // 0x08B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FName                                   PlayerStatus;                                      // 0x08C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   AbilityWidgets;                                    // 0x08D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_WeakenObjective_DamageResist;                   // 0x08D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    WaitingForInput_Seq;                               // 0x08E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerBotSpawner*                      BotSpawner_InhibAggro;                             // 0x08E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOrionAIBot*                            EnemyBot_InhibAggro;                               // 0x08F0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 EnemyBotRetreatActor;                              // 0x08F8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 EnemyBotFightMinionsActor;                         // 0x0900(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       Tutorial_1v1_Learn_Inhib_Friendly;                 // 0x0908(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       Tutorial_1v1_Learn_Tower_Friendly;                 // 0x0918(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_EnemyRetreat_LowHealth;                         // 0x0928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBehaviorTree*                          BT_AttackEnemies;                                  // 0x0930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 EnemyBotRetreatOtherActor;                         // 0x0938(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_LookAt_UltimateAbility;                         // 0x0940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    UltimateAbility_Seq;                               // 0x0948(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       Tutorial_1v1_Learn_Core_Friendly;                  // 0x0950(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  GE_HighlightObject;                                // 0x0960(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 GE_EnemyBot_DamageResist;                          // 0x0980(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       tutorial_1v1_kill_enemy_hero;                      // 0x0988(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_FirstSpawn_Move;                                // 0x0998(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOrionBaseActor*                        HomeBase_Red;                                      // 0x09A0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_EnemyHero_Introduction;                         // 0x09A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_EnemyHero_Killed;                               // 0x09B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       tutorial_1v1_started;                              // 0x09B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       tutorial_1v1_complete;                             // 0x09C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayStatTag                       Tutorial_1v1_Tower_Aggro_Hero;                     // 0x09D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UEnvQuery>               EQS_WeightedEnemyHero;                             // 0x09E8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<struct FGameplayStatTag>               TutorialStats;                                     // 0x0A08(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	struct FGameplayTag                           NewVar_0;                                          // 0x0A18(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_GSM_MOBA_1v1_Tutorial(int32 EntryPoint);
	void CoreAggroMinionFinished();
	void CoreAggroHeroFinished();
	void UltimateAbilityFinished();
	void InhibAggroHeroEnemyDamageFinished();
	void InhibAggroMinionFinished();
	void InhibAggroHeroFinished();
	void FirstAbilityFinished();
	void TowerAggroMinionFinished();
	void TowerAggroHeroFinished();
	void FirstCombatFinished();
	void FirstSpawnFinished();
	void StartBotSpawner();
	void OnDeath_EnemyBot_Bind(class AOrionChar* DeadChar, class AController* Killer, class AActor* DamageCauser);
	void OnActorEndOverlap_CoreFriendly_Bind(class AActor* OverlappedActor, class AActor* OtherActor);
	void StartUltimateAbilityTutorial();
	void StartEnemyBotAfterInhibAggro();
	void OnActorEndOverlap_TowerFriendly_Bind(class AActor* OverlappedActor, class AActor* OtherActor);
	void OnActorEndOverlap_InhibFriendly_Bind(class AActor* OverlappedActor, class AActor* OtherActor);
	void EndTheTutorial(const struct FGameplayStatTag& Stat);
	void OnBotFinishedSpawning_Bind(class AOrionAIBot* Bot);
	void StartLaneSpawners();
	void StartEnemyBotInhibAggro();
	void OnFormationKilled_Blue_Bind(class AOrionCharAISpawner* AISpawner, class AController* Killer);
	void OnFormationFinishedSpawning_Red_Bind(class AOrionCharAISpawner* AISpawner);
	void OnGameReady();
	void DeathHandler_Core_Bind(class AController* Killer, class AActor* DamageCauser);
	void DeathHandler_Inhib_Bind(class AController* Killer, class AActor* DamageCauser);
	void UpdateStat(const struct FGameplayStatTag& StatName, float Delay);
	void DeathHandler_Tower_Bind(class AController* Killer, class AActor* DamageCauser);
	void StartTheTutorial(const struct FGameplayStatTag& Stat);
	void OnActorBeginOverlap_CoreAggro_Bind(class AActor* OverlappedActor, class AActor* OtherActor);
	void OnActorBeginOverlap_InhibAggro_Bind(class AActor* OverlappedActor, class AActor* OtherActor);
	void OnActorBeginOverlap_TowerAggro_Bind(class AActor* OverlappedActor, class AActor* OtherActor);
	void StartFirstAbilityTutorial();
	void OnFormationFinishedSpawning_Blue_Bind(class AOrionCharAISpawner* AISpawner);
	void OnSuccess_6764E2824DB4C3766814718CE824E643(EPathFollowingResult MovementResult);
	void OnFail_6764E2824DB4C3766814718CE824E643(EPathFollowingResult MovementResult);
	void OnSuccess_77DDBB544355966C6D54AA90D7732D40(EPathFollowingResult MovementResult);
	void OnFail_77DDBB544355966C6D54AA90D7732D40(EPathFollowingResult MovementResult);
	void UserConstructionScript();
	void RegisterCore_Red(class AOrionDamageableObjective_Base* Actor);
	void RegisterInhib_Red(class AOrionDamageableObjective_Base* Actor);
	void RegisterTower_Red(class AOrionDamageableObjective_Base* Actor);
	void RegisterCoreSeq_Red(class ALevelSequenceActor* Sequencer);
	void RegisterInhibSeq_Red(class ALevelSequenceActor* Sequencer);
	void RegisterTowerSeq_Red(class ALevelSequenceActor* Sequencer);
	void RegisterCoreLookAt_Red(class AActor* Actor);
	void RegisterInhibLookAt_Red(class AActor* Actor);
	void RegisterTowerLookAt_Red(class AActor* Actor);
	void RegisterCore_Blue(class AOrionDamageableObjective_Base* Actor);
	void RegisterInhib_Blue(class AOrionDamageableObjective_Base* Actor);
	void RegisterTower_Blue(class AOrionDamageableObjective_Base* Actor);
	void IsMatchOver(bool* GameOver);
	void RegisterWelcomeSeq(class ALevelSequenceActor* Sequencer);
	void RegisterAISpawner_Red(class ABP_OrionCharAISpawner_C* Spawner);
	void RegisterAISpawner_Blue(class ABP_OrionCharAISpawner_C* Spawner);
	void RegisterMinionsLookAt_FirstCombat(class AActor* Actor);
	void RegisterFirstCombatSeq(class ALevelSequenceActor* Sequencer);
	void RegisterFirstAbilitySeq(class ALevelSequenceActor* Sequencer);
	void RegisterPauseSeq(class ALevelSequenceActor* Sequencer);
	void RegisterUnpauseSeq(class ALevelSequenceActor* Sequencer);
	void OnRep_AISpawner_Blue();
	void RegisterTowerLookAt_Blue(class AActor* Actor);
	void RegisterTowerSeq_Blue(class ALevelSequenceActor* Sequencer);
	void OnRep_Tower_Blue();
	void OnRep_Inhib_Blue();
	void OnRep_Core_Blue();
	void RegisterInhibLookAt_Blue(class AActor* Actor);
	void RegisterCoreLookAt_Blue(class AActor* Actor);
	void RegisterInhibSeq_Blue(class ALevelSequenceActor* Sequencer);
	void RegisterCoreSeq_Blue(class ALevelSequenceActor* Sequencer);
	void OnRep_AISpawner_Red();
	void RegisterWaitingForInputSeq(class ALevelSequenceActor* Sequencer);
	void RegisterBotSpawner_InhibAggro(class APlayerBotSpawner* BotSpawner);
	void RegisterEnemyBotRetreatActor(class AActor* Actor);
	void RegisterEnemyBotFightMinionsActor(class AActor* Actor);
	void OnRep_Inhib_Red();
	void OnRep_Tower_Red();
	void RegisterEnemyBotRetreatOtherActor(class AActor* Actor);
	void RegisterUltimateAbilitySeq(class ALevelSequenceActor* Sequencer);
	void OnRep_Core_Red();
	void GetTutorialPlayerController(class AOrionPlayerController_Tutorial** AsOrion_Player_Controller_Tutorial);
	void TutorialPlayerApplyGameplayEffect(class UClass* GameplayEffect);
	void RegisterHomeBase_Red(class AOrionBaseActor* Actor);
	void EndThePause();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GSM_MOBA_1v1_Tutorial_C">();
	}
	static class ABP_GSM_MOBA_1v1_Tutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GSM_MOBA_1v1_Tutorial_C>();
	}
};
static_assert(alignof(ABP_GSM_MOBA_1v1_Tutorial_C) == 0x000010, "Wrong alignment on ABP_GSM_MOBA_1v1_Tutorial_C");
static_assert(sizeof(ABP_GSM_MOBA_1v1_Tutorial_C) == 0x000A20, "Wrong size on ABP_GSM_MOBA_1v1_Tutorial_C");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, UberGraphFrame) == 0x000760, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, DefaultSceneRoot) == 0x000768, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Core_Red) == 0x000770, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Core_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Inhib_Red) == 0x000778, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Inhib_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tower_Red) == 0x000780, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tower_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Core_Seq_Red) == 0x000788, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Core_Seq_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Inhib_Seq_Red) == 0x000790, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Inhib_Seq_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tower_Seq_Red) == 0x000798, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tower_Seq_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Core_LookAt_Red) == 0x0007A0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Core_LookAt_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Inhib_LookAt_Red) == 0x0007A8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Inhib_LookAt_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tower_LookAt_Red) == 0x0007B0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tower_LookAt_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Core_Blue) == 0x0007B8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Core_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Inhib_Blue) == 0x0007C0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Inhib_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tower_Blue) == 0x0007C8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tower_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tutorial_FirstSpawn) == 0x0007D0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tutorial_FirstSpawn' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Welcome_Seq) == 0x0007D8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Welcome_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, AISpawner_Blue) == 0x0007E0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::AISpawner_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, AISpawner_Red) == 0x0007E8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::AISpawner_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Minions_LookAt_FirstCombat) == 0x0007F0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Minions_LookAt_FirstCombat' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, FirstCombat_Seq) == 0x0007F8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::FirstCombat_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, FirstAbility_Seq) == 0x000800, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::FirstAbility_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, TutorialClasses) == 0x000808, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::TutorialClasses' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Pause_Seq) == 0x000818, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Pause_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Unpause_Seq) == 0x000820, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Unpause_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_WeakenAI_Health) == 0x000828, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_WeakenAI_Health' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_LookAt_FirstAbility) == 0x000830, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_LookAt_FirstAbility' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tower_LookAt_Blue) == 0x000838, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tower_LookAt_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tower_Seq_Blue) == 0x000840, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tower_Seq_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_Tower_Aggro_Hero) == 0x000848, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_Tower_Aggro_Hero' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_Tower_Aggro_Minion) == 0x000850, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_Tower_Aggro_Minion' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Inhib_LookAt_Blue) == 0x000858, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Inhib_LookAt_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Core_LookAt_Blue) == 0x000860, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Core_LookAt_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Core_Seq_Blue) == 0x000868, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Core_Seq_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Inhib_Seq_Blue) == 0x000870, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Inhib_Seq_Blue' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_Inhib_Aggro_Hero) == 0x000878, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_Inhib_Aggro_Hero' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_Inhib_Aggro_Minion) == 0x000880, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_Inhib_Aggro_Minion' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_Core_Aggro_Hero) == 0x000888, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_Core_Aggro_Hero' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_Core_Aggro_Minion) == 0x000890, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_Core_Aggro_Minion' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, tutorial_1v1_tower_destroy) == 0x000898, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::tutorial_1v1_tower_destroy' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, tutorial_1v1_inhib_destroy) == 0x0008A8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::tutorial_1v1_inhib_destroy' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, tutorial_1v1_core_destroy) == 0x0008B8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::tutorial_1v1_core_destroy' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, PlayerStatus) == 0x0008C8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::PlayerStatus' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, AbilityWidgets) == 0x0008D0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::AbilityWidgets' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_WeakenObjective_DamageResist) == 0x0008D8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_WeakenObjective_DamageResist' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, WaitingForInput_Seq) == 0x0008E0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::WaitingForInput_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, BotSpawner_InhibAggro) == 0x0008E8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::BotSpawner_InhibAggro' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, EnemyBot_InhibAggro) == 0x0008F0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::EnemyBot_InhibAggro' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, EnemyBotRetreatActor) == 0x0008F8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::EnemyBotRetreatActor' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, EnemyBotFightMinionsActor) == 0x000900, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::EnemyBotFightMinionsActor' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tutorial_1v1_Learn_Inhib_Friendly) == 0x000908, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tutorial_1v1_Learn_Inhib_Friendly' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tutorial_1v1_Learn_Tower_Friendly) == 0x000918, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tutorial_1v1_Learn_Tower_Friendly' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_EnemyRetreat_LowHealth) == 0x000928, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_EnemyRetreat_LowHealth' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, BT_AttackEnemies) == 0x000930, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::BT_AttackEnemies' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, EnemyBotRetreatOtherActor) == 0x000938, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::EnemyBotRetreatOtherActor' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_LookAt_UltimateAbility) == 0x000940, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_LookAt_UltimateAbility' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, UltimateAbility_Seq) == 0x000948, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::UltimateAbility_Seq' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tutorial_1v1_Learn_Core_Friendly) == 0x000950, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tutorial_1v1_Learn_Core_Friendly' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_HighlightObject) == 0x000960, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_HighlightObject' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_EnemyBot_DamageResist) == 0x000980, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_EnemyBot_DamageResist' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, tutorial_1v1_kill_enemy_hero) == 0x000988, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::tutorial_1v1_kill_enemy_hero' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_FirstSpawn_Move) == 0x000998, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_FirstSpawn_Move' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, HomeBase_Red) == 0x0009A0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::HomeBase_Red' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_EnemyHero_Introduction) == 0x0009A8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_EnemyHero_Introduction' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, GE_EnemyHero_Killed) == 0x0009B0, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::GE_EnemyHero_Killed' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, tutorial_1v1_started) == 0x0009B8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::tutorial_1v1_started' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, tutorial_1v1_complete) == 0x0009C8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::tutorial_1v1_complete' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, Tutorial_1v1_Tower_Aggro_Hero) == 0x0009D8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::Tutorial_1v1_Tower_Aggro_Hero' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, EQS_WeightedEnemyHero) == 0x0009E8, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::EQS_WeightedEnemyHero' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, TutorialStats) == 0x000A08, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::TutorialStats' has a wrong offset!");
static_assert(offsetof(ABP_GSM_MOBA_1v1_Tutorial_C, NewVar_0) == 0x000A18, "Member 'ABP_GSM_MOBA_1v1_Tutorial_C::NewVar_0' has a wrong offset!");

}

