#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Default

#include "Basic.hpp"

#include "ButtonStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Default.ButtonStyle-Default_C
// 0x0000 (0x0CA0 - 0x0CA0)
class UButtonStyle_Default_C final : public UButtonStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Default_C">();
	}
	static class UButtonStyle_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Default_C>();
	}
};
static_assert(alignof(UButtonStyle_Default_C) == 0x000008, "Wrong alignment on UButtonStyle_Default_C");
static_assert(sizeof(UButtonStyle_Default_C) == 0x000CA0, "Wrong size on UButtonStyle_Default_C");

}

