#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CardPackOpenScreen

#include "Basic.hpp"

#include "CardPackOpenScreen_classes.hpp"
#include "CardPackOpenScreen_parameters.hpp"


namespace SDK
{

// Function CardPackOpenScreen.CardPackOpenScreen_C.ExecuteUbergraph_CardPackOpenScreen
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCardPackOpenScreen_C::ExecuteUbergraph_CardPackOpenScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "ExecuteUbergraph_CardPackOpenScreen");

	Params::CardPackOpenScreen_C_ExecuteUbergraph_CardPackOpenScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnResetForNextPack
// (Event, Protected, BlueprintEvent)

void UCardPackOpenScreen_C::OnResetForNextPack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnResetForNextPack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnActivePackSet
// (Event, Protected, BlueprintEvent)

void UCardPackOpenScreen_C::OnActivePackSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnActivePackSet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__ExclusiveModeMenu_K2Node_ComponentBoundEvent_666_OnBackClicked__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__ExclusiveModeMenu_K2Node_ComponentBoundEvent_666_OnBackClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__ExclusiveModeMenu_K2Node_ComponentBoundEvent_666_OnBackClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnDeactivated
// (Event, Protected, BlueprintEvent)

void UCardPackOpenScreen_C::OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__DefaultButtonAccept_K2Node_ComponentBoundEvent_703_OrionBaseButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UOrionBaseButton*                 Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCardPackOpenScreen_C::BndEvt__DefaultButtonAccept_K2Node_ComponentBoundEvent_703_OrionBaseButtonClicked__DelegateSignature(class UOrionBaseButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__DefaultButtonAccept_K2Node_ComponentBoundEvent_703_OrionBaseButtonClicked__DelegateSignature");

	Params::CardPackOpenScreen_C_BndEvt__DefaultButtonAccept_K2Node_ComponentBoundEvent_703_OrionBaseButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnAllCardsRevealed
// (Event, Protected, BlueprintEvent)

void UCardPackOpenScreen_C::OnAllCardsRevealed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnAllCardsRevealed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnPackOpened
// (Event, Protected, BlueprintEvent)
// Parameters:
// EOrionItemRarity                        Rarity                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCardPackOpenScreen_C::OnPackOpened(EOrionItemRarity Rarity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnPackOpened");

	Params::CardPackOpenScreen_C_OnPackOpened Parms{};

	Parms.Rarity = Rarity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnBeginPackOpen
// (Event, Protected, BlueprintEvent)

void UCardPackOpenScreen_C::OnBeginPackOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnBeginPackOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__RevealCards_K2Node_ComponentBoundEvent_12_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__RevealCards_K2Node_ComponentBoundEvent_12_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__RevealCards_K2Node_ComponentBoundEvent_12_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__RevealCards_K2Node_ComponentBoundEvent_9_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__RevealCards_K2Node_ComponentBoundEvent_9_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__RevealCards_K2Node_ComponentBoundEvent_9_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__OpenAppear_K2Node_ComponentBoundEvent_2430_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__OpenAppear_K2Node_ComponentBoundEvent_2430_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__OpenAppear_K2Node_ComponentBoundEvent_2430_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__OpenAppear_K2Node_ComponentBoundEvent_2409_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__OpenAppear_K2Node_ComponentBoundEvent_2409_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__OpenAppear_K2Node_ComponentBoundEvent_2409_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UCardPackOpenScreen_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__AcceptDisappear_K2Node_ComponentBoundEvent_1464_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__AcceptDisappear_K2Node_ComponentBoundEvent_1464_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__AcceptDisappear_K2Node_ComponentBoundEvent_1464_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__RemoveCards_K2Node_ComponentBoundEvent_1446_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__RemoveCards_K2Node_ComponentBoundEvent_1446_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__RemoveCards_K2Node_ComponentBoundEvent_1446_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__RevealAllAppear_K2Node_ComponentBoundEvent_1334_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__RevealAllAppear_K2Node_ComponentBoundEvent_1334_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__RevealAllAppear_K2Node_ComponentBoundEvent_1334_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__RevealAllAppear_K2Node_ComponentBoundEvent_1318_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__RevealAllAppear_K2Node_ComponentBoundEvent_1318_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__RevealAllAppear_K2Node_ComponentBoundEvent_1318_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__AcceptAppear_K2Node_ComponentBoundEvent_861_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__AcceptAppear_K2Node_ComponentBoundEvent_861_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__AcceptAppear_K2Node_ComponentBoundEvent_861_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__AcceptAppear_K2Node_ComponentBoundEvent_849_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__AcceptAppear_K2Node_ComponentBoundEvent_849_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__AcceptAppear_K2Node_ComponentBoundEvent_849_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.BndEvt__RemoveCards_K2Node_ComponentBoundEvent_1363_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature
// (BlueprintEvent)

void UCardPackOpenScreen_C::BndEvt__RemoveCards_K2Node_ComponentBoundEvent_1363_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "BndEvt__RemoveCards_K2Node_ComponentBoundEvent_1363_OnWidgetAnimationPlaybackStatusChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CardPackOpenScreen.CardPackOpenScreen_C.UpdateAffinityColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UCardPackOpenScreen_C::UpdateAffinityColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardPackOpenScreen_C", "UpdateAffinityColor");

	UObject::ProcessEvent(Func, nullptr);
}

}

