#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CardShopDeckCardRenderer

#include "Basic.hpp"

#include "CardShopDeckCardRenderer_classes.hpp"
#include "CardShopDeckCardRenderer_parameters.hpp"


namespace SDK
{

// Function CardShopDeckCardRenderer.CardShopDeckCardRenderer_C.ExecuteUbergraph_CardShopDeckCardRenderer
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCardShopDeckCardRenderer_C::ExecuteUbergraph_CardShopDeckCardRenderer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardShopDeckCardRenderer_C", "ExecuteUbergraph_CardShopDeckCardRenderer");

	Params::CardShopDeckCardRenderer_C_ExecuteUbergraph_CardShopDeckCardRenderer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CardShopDeckCardRenderer.CardShopDeckCardRenderer_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, Parm, OutParm, ReferenceParm)

void UCardShopDeckCardRenderer_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardShopDeckCardRenderer_C", "OnMouseLeave");

	Params::CardShopDeckCardRenderer_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CardShopDeckCardRenderer.CardShopDeckCardRenderer_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, Parm, OutParm, ReferenceParm)

void UCardShopDeckCardRenderer_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardShopDeckCardRenderer_C", "OnMouseEnter");

	Params::CardShopDeckCardRenderer_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CardShopDeckCardRenderer.CardShopDeckCardRenderer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCardShopDeckCardRenderer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CardShopDeckCardRenderer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

