#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DailyLoginRewardScreen

#include "Basic.hpp"

#include "OrionUI_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function DailyLoginRewardScreen.DailyLoginRewardScreen_C.ExecuteUbergraph_DailyLoginRewardScreen
// 0x0100 (0x0100 - 0x0000)
struct DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable2;                             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable3;                             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOrionDailyRewardPreviewTotalDays             Temp_byte_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0024(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable2;                             // 0x0034(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable3;                             // 0x0044(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable4;                             // 0x0054(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bDidPreviewDayChange;                 // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_Percent;                              // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOrionDailyRewardPreviewTotalDays             K2Node_Event_TotalDays;                            // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UOrionDailyRewardItem*>          K2Node_MakeArray_Array;                            // 0x0070(0x0010)(ZeroConstructor, ReferenceParm)
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0080(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     Temp_object_Variable4;                             // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetDesiredSize_ReturnValue;               // 0x00A0(0x0008)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X;                          // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue2;         // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x00B8(0x0008)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDailyRewardItem_C*                     K2Node_DynamicCast_AsDaily_Reward_Item;            // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOrionBaseButton*                       K2Node_ComponentBoundEvent_Button;                 // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOrionDailyRewardPreviewTotalDays             Temp_byte_Variable2;                               // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     K2Node_Select2_Default;                            // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDailyRewardItem_C*                     K2Node_DynamicCast_AsDaily_Reward_Item2;           // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bCanClaim;                            // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen) == 0x000008, "Wrong alignment on DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen");
static_assert(sizeof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen) == 0x000100, "Wrong size on DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, EntryPoint) == 0x000000, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_object_Variable) == 0x000008, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_object_Variable2) == 0x000010, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_object_Variable2' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_object_Variable3) == 0x000018, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_object_Variable3' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_byte_Variable) == 0x000020, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_struct_Variable) == 0x000024, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_struct_Variable2) == 0x000034, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_struct_Variable2' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_struct_Variable3) == 0x000044, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_struct_Variable3' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_struct_Variable4) == 0x000054, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_struct_Variable4' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_Event_bDidPreviewDayChange) == 0x000064, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_Event_bDidPreviewDayChange' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_Event_Percent) == 0x000068, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_Event_Percent' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_Event_TotalDays) == 0x00006C, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_Event_TotalDays' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_MakeArray_Array) == 0x000070, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_Select_Default) == 0x000080, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000090, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_object_Variable4) == 0x000098, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_object_Variable4' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_GetDesiredSize_ReturnValue) == 0x0000A0, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_GetDesiredSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_BreakVector2D_X) == 0x0000A8, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_BreakVector2D_Y) == 0x0000AC, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0000B0, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_Subtract_FloatFloat_ReturnValue2) == 0x0000B4, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_Subtract_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_MakeVector2D_ReturnValue) == 0x0000B8, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, CallFunc_GetDynamicMaterial_ReturnValue) == 0x0000C0, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_DynamicCast_AsDaily_Reward_Item) == 0x0000C8, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_DynamicCast_AsDaily_Reward_Item' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_DynamicCast_bSuccess) == 0x0000D0, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_ComponentBoundEvent_Button) == 0x0000D8, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, Temp_byte_Variable2) == 0x0000E0, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_Select2_Default) == 0x0000E8, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_DynamicCast_AsDaily_Reward_Item2) == 0x0000F0, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_DynamicCast_AsDaily_Reward_Item2' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_DynamicCast_bSuccess2) == 0x0000F8, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen, K2Node_Event_bCanClaim) == 0x0000F9, "Member 'DailyLoginRewardScreen_C_ExecuteUbergraph_DailyLoginRewardScreen::K2Node_Event_bCanClaim' has a wrong offset!");

// Function DailyLoginRewardScreen.DailyLoginRewardScreen_C.OnDataSet
// 0x0001 (0x0001 - 0x0000)
struct DailyLoginRewardScreen_C_OnDataSet final
{
public:
	bool                                          bCanClaim;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DailyLoginRewardScreen_C_OnDataSet) == 0x000001, "Wrong alignment on DailyLoginRewardScreen_C_OnDataSet");
static_assert(sizeof(DailyLoginRewardScreen_C_OnDataSet) == 0x000001, "Wrong size on DailyLoginRewardScreen_C_OnDataSet");
static_assert(offsetof(DailyLoginRewardScreen_C_OnDataSet, bCanClaim) == 0x000000, "Member 'DailyLoginRewardScreen_C_OnDataSet::bCanClaim' has a wrong offset!");

// Function DailyLoginRewardScreen.DailyLoginRewardScreen_C.BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature final
{
public:
	class UOrionBaseButton*                       Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature");
static_assert(sizeof(DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong size on DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature");
static_assert(offsetof(DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'DailyLoginRewardScreen_C_BndEvt__Button_Close_K2Node_ComponentBoundEvent_48_OrionBaseButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function DailyLoginRewardScreen.DailyLoginRewardScreen_C.OnPreviewPercentSet
// 0x0008 (0x0008 - 0x0000)
struct DailyLoginRewardScreen_C_OnPreviewPercentSet final
{
public:
	float                                         Percent;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EOrionDailyRewardPreviewTotalDays             TotalDays;                                         // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DailyLoginRewardScreen_C_OnPreviewPercentSet) == 0x000004, "Wrong alignment on DailyLoginRewardScreen_C_OnPreviewPercentSet");
static_assert(sizeof(DailyLoginRewardScreen_C_OnPreviewPercentSet) == 0x000008, "Wrong size on DailyLoginRewardScreen_C_OnPreviewPercentSet");
static_assert(offsetof(DailyLoginRewardScreen_C_OnPreviewPercentSet, Percent) == 0x000000, "Member 'DailyLoginRewardScreen_C_OnPreviewPercentSet::Percent' has a wrong offset!");
static_assert(offsetof(DailyLoginRewardScreen_C_OnPreviewPercentSet, TotalDays) == 0x000004, "Member 'DailyLoginRewardScreen_C_OnPreviewPercentSet::TotalDays' has a wrong offset!");

// Function DailyLoginRewardScreen.DailyLoginRewardScreen_C.OnClaim
// 0x0001 (0x0001 - 0x0000)
struct DailyLoginRewardScreen_C_OnClaim final
{
public:
	bool                                          bDidPreviewDayChange;                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DailyLoginRewardScreen_C_OnClaim) == 0x000001, "Wrong alignment on DailyLoginRewardScreen_C_OnClaim");
static_assert(sizeof(DailyLoginRewardScreen_C_OnClaim) == 0x000001, "Wrong size on DailyLoginRewardScreen_C_OnClaim");
static_assert(offsetof(DailyLoginRewardScreen_C_OnClaim, bDidPreviewDayChange) == 0x000000, "Member 'DailyLoginRewardScreen_C_OnClaim::bDidPreviewDayChange' has a wrong offset!");

}

