#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FrontEndPartyMember

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "OrionGame_structs.hpp"
#include "UMG_structs.hpp"
#include "Party_structs.hpp"


namespace SDK::Params
{

// Function FrontEndPartyMember.FrontEndPartyMember_C.ExecuteUbergraph_FrontEndPartyMember
// 0x0060 (0x0060 - 0x0000)
struct FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_ShouldOpenDueToClick_ReturnValue;         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bIsOpen2;               // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bIsOpen;                // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ShouldOpenDueToClick_ReturnValue2;        // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOrionBaseButton*                       K2Node_ComponentBoundEvent_Button4;                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Selected2;              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOrionBaseButton*                       K2Node_ComponentBoundEvent_Button3;                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOrionBaseButton*                       K2Node_ComponentBoundEvent_Button2;                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Selected;               // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOrionBaseButton*                       K2Node_ComponentBoundEvent_Button;                 // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPartyContextMenu_C*                    CallFunc_Create_ReturnValue;                       // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember");
static_assert(sizeof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember) == 0x000060, "Wrong size on FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, EntryPoint) == 0x000000, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::EntryPoint' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, CallFunc_ShouldOpenDueToClick_ReturnValue) == 0x000018, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::CallFunc_ShouldOpenDueToClick_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_bIsOpen2) == 0x000019, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_bIsOpen2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_bIsOpen) == 0x00001A, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_bIsOpen' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, CallFunc_ShouldOpenDueToClick_ReturnValue2) == 0x00001B, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::CallFunc_ShouldOpenDueToClick_ReturnValue2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_Button4) == 0x000020, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_Button4' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_Selected2) == 0x000028, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_Selected2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_Button3) == 0x000030, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_Button3' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_Button2) == 0x000038, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_Button2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_Selected) == 0x000040, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_Selected' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, K2Node_ComponentBoundEvent_Button) == 0x000048, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, CallFunc_GetOwningPlayer_ReturnValue) == 0x000050, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember, CallFunc_Create_ReturnValue) == 0x000058, "Member 'FrontEndPartyMember_C_ExecuteUbergraph_FrontEndPartyMember::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature final
{
public:
	class UOrionBaseButton*                       Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature");
static_assert(sizeof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong size on FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1028_OrionBaseButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature final
{
public:
	class UOrionBaseButton*                       Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Selected;                                          // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature");
static_assert(sizeof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature) == 0x000010, "Wrong size on FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature, Button) == 0x000000, "Member 'FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature::Button' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature, Selected) == 0x000008, "Member 'FrontEndPartyMember_C_BndEvt__SelectableIconButtonMember_K2Node_ComponentBoundEvent_1017_OrionSelectedStateChanged__DelegateSignature::Selected' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature final
{
public:
	class UOrionBaseButton*                       Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature");
static_assert(sizeof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong size on FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_72_OrionBaseButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature final
{
public:
	class UOrionBaseButton*                       Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Selected;                                          // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature");
static_assert(sizeof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature) == 0x000010, "Wrong size on FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature, Button) == 0x000000, "Member 'FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature::Button' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature, Selected) == 0x000008, "Member 'FrontEndPartyMember_C_BndEvt__SelectableIconButtonInvite_K2Node_ComponentBoundEvent_61_OrionSelectedStateChanged__DelegateSignature::Selected' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.BndEvt__[Anchor] Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature final
{
public:
	bool                                          bIsOpen;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature) == 0x000001, "Wrong alignment on FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature");
static_assert(sizeof(FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature) == 0x000001, "Wrong size on FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature, bIsOpen) == 0x000000, "Member 'FrontEndPartyMember_C_BndEvt___Anchor__Invite_K2Node_ComponentBoundEvent_511_OnMenuOpenChangedEvent__DelegateSignature::bIsOpen' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.BndEvt__[Anchor] Party Member Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature final
{
public:
	bool                                          bIsOpen;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature) == 0x000001, "Wrong alignment on FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature");
static_assert(sizeof(FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature) == 0x000001, "Wrong size on FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature");
static_assert(offsetof(FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature, bIsOpen) == 0x000000, "Member 'FrontEndPartyMember_C_BndEvt___Anchor__Party_Member_Options_K2Node_ComponentBoundEvent_504_OnMenuOpenChangedEvent__DelegateSignature::bIsOpen' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.UpdatePartyMember
// 0x00B0 (0x00B0 - 0x0000)
struct FrontEndPartyMember_C_UpdatePartyMember final
{
public:
	class UOrionPersistentPartyMember*            Party_Member;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_MakeBrushFromTexture_ReturnValue;         // 0x0008(0x0090)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0098(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FrontEndPartyMember_C_UpdatePartyMember) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_UpdatePartyMember");
static_assert(sizeof(FrontEndPartyMember_C_UpdatePartyMember) == 0x0000B0, "Wrong size on FrontEndPartyMember_C_UpdatePartyMember");
static_assert(offsetof(FrontEndPartyMember_C_UpdatePartyMember, Party_Member) == 0x000000, "Member 'FrontEndPartyMember_C_UpdatePartyMember::Party_Member' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_UpdatePartyMember, CallFunc_MakeBrushFromTexture_ReturnValue) == 0x000008, "Member 'FrontEndPartyMember_C_UpdatePartyMember::CallFunc_MakeBrushFromTexture_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_UpdatePartyMember, K2Node_CreateDelegate_OutputDelegate) == 0x000098, "Member 'FrontEndPartyMember_C_UpdatePartyMember::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_UpdatePartyMember, CallFunc_IsValid_ReturnValue) == 0x0000A8, "Member 'FrontEndPartyMember_C_UpdatePartyMember::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.GetPartyMemberContextMenu
// 0x0018 (0x0018 - 0x0000)
struct FrontEndPartyMember_C_GetPartyMemberContextMenu final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPartyContext*                          CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_NumPartyMembers_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FrontEndPartyMember_C_GetPartyMemberContextMenu) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_GetPartyMemberContextMenu");
static_assert(sizeof(FrontEndPartyMember_C_GetPartyMemberContextMenu) == 0x000018, "Wrong size on FrontEndPartyMember_C_GetPartyMemberContextMenu");
static_assert(offsetof(FrontEndPartyMember_C_GetPartyMemberContextMenu, ReturnValue) == 0x000000, "Member 'FrontEndPartyMember_C_GetPartyMemberContextMenu::ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_GetPartyMemberContextMenu, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'FrontEndPartyMember_C_GetPartyMemberContextMenu::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_GetPartyMemberContextMenu, CallFunc_NumPartyMembers_ReturnValue) == 0x000010, "Member 'FrontEndPartyMember_C_GetPartyMemberContextMenu::CallFunc_NumPartyMembers_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_GetPartyMemberContextMenu, CallFunc_Greater_IntInt_ReturnValue) == 0x000014, "Member 'FrontEndPartyMember_C_GetPartyMemberContextMenu::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.Refresh Widget
// 0x0210 (0x0210 - 0x0000)
struct FrontEndPartyMember_C_Refresh_Widget final
{
public:
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0008(0x0018)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue2;             // 0x0020(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EOrionBanReason                               CallFunc_GetCurrentBanReason_ReturnValue;          // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UPartyContext*                          CallFunc_GetContext_ReturnValue;                   // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHeroContext*                           CallFunc_GetContext_ReturnValue2;                  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_NumPartyMembers_ReturnValue;              // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetEmptyText_ReturnValue;                 // 0x0058(0x0018)()
	struct FSlateBrush                            CallFunc_MakeBrushFromTexture_ReturnValue;         // 0x0070(0x0090)()
	class UPartyContext*                          CallFunc_GetContext_ReturnValue3;                  // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_NumPartyMembers_ReturnValue2;             // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPartyType                                    CallFunc_GetPartyPrivacySetting_OutPartyType;      // 0x010C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetPartyPrivacySetting_OutLeaderFriendsOnly; // 0x010D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetPartyPrivacySetting_OutLeaderInvitesOnly; // 0x010E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetPartyPrivacySetting_ReturnValue;       // 0x010F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0112(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsReady_ReturnValue;                      // 0x0113(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue2;                   // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable2;                               // 0x0115(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0116(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable3;                               // 0x0117(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable4;                               // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetHero_ReturnValue;                      // 0x0120(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_131[0x7];                                      // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOrionHeroData*                         CallFunc_GetHeroByString_ReturnValue;              // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             CallFunc_GetIcon_ReturnValue;                      // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0150(0x0090)()
	bool                                          CallFunc_IsPartyLeader_ReturnValue;                // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E1[0x3];                                      // 0x01E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetAccountLevel_ReturnValue;              // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x01F0(0x0018)()
	ESlateVisibility                              K2Node_Select2_Default;                            // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FrontEndPartyMember_C_Refresh_Widget) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_Refresh_Widget");
static_assert(sizeof(FrontEndPartyMember_C_Refresh_Widget) == 0x000210, "Wrong size on FrontEndPartyMember_C_Refresh_Widget");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, Temp_byte_Variable) == 0x000000, "Member 'FrontEndPartyMember_C_Refresh_Widget::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, Temp_byte_Variable2) == 0x000001, "Member 'FrontEndPartyMember_C_Refresh_Widget::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_MakeLiteralText_ReturnValue) == 0x000008, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_MakeLiteralText_ReturnValue2) == 0x000020, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_MakeLiteralText_ReturnValue2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, Temp_bool_Variable) == 0x000038, "Member 'FrontEndPartyMember_C_Refresh_Widget::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetCurrentBanReason_ReturnValue) == 0x000039, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetCurrentBanReason_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, K2Node_SwitchEnum_CmpSuccess) == 0x00003A, "Member 'FrontEndPartyMember_C_Refresh_Widget::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetContext_ReturnValue) == 0x000040, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetContext_ReturnValue2) == 0x000048, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetContext_ReturnValue2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_NumPartyMembers_ReturnValue) == 0x000050, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_NumPartyMembers_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_Greater_IntInt_ReturnValue) == 0x000054, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetEmptyText_ReturnValue) == 0x000058, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetEmptyText_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_MakeBrushFromTexture_ReturnValue) == 0x000070, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_MakeBrushFromTexture_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetContext_ReturnValue3) == 0x000100, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetContext_ReturnValue3' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_NumPartyMembers_ReturnValue2) == 0x000108, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_NumPartyMembers_ReturnValue2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetPartyPrivacySetting_OutPartyType) == 0x00010C, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetPartyPrivacySetting_OutPartyType' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetPartyPrivacySetting_OutLeaderFriendsOnly) == 0x00010D, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetPartyPrivacySetting_OutLeaderFriendsOnly' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetPartyPrivacySetting_OutLeaderInvitesOnly) == 0x00010E, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetPartyPrivacySetting_OutLeaderInvitesOnly' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetPartyPrivacySetting_ReturnValue) == 0x00010F, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetPartyPrivacySetting_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000110, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_Not_PreBool_ReturnValue) == 0x000111, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_BooleanOR_ReturnValue) == 0x000112, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_IsReady_ReturnValue) == 0x000113, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_IsReady_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_BooleanOR_ReturnValue2) == 0x000114, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_BooleanOR_ReturnValue2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, Temp_bool_Variable2) == 0x000115, "Member 'FrontEndPartyMember_C_Refresh_Widget::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_IsValid_ReturnValue) == 0x000116, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, Temp_byte_Variable3) == 0x000117, "Member 'FrontEndPartyMember_C_Refresh_Widget::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, Temp_byte_Variable4) == 0x000118, "Member 'FrontEndPartyMember_C_Refresh_Widget::Temp_byte_Variable4' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetHero_ReturnValue) == 0x000120, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetHero_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, K2Node_Select_Default) == 0x000130, "Member 'FrontEndPartyMember_C_Refresh_Widget::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetHeroByString_ReturnValue) == 0x000138, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetHeroByString_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_IsValid_ReturnValue2) == 0x000140, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetIcon_ReturnValue) == 0x000148, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetIcon_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, K2Node_MakeStruct_SlateBrush) == 0x000150, "Member 'FrontEndPartyMember_C_Refresh_Widget::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_IsPartyLeader_ReturnValue) == 0x0001E0, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_IsPartyLeader_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_GetAccountLevel_ReturnValue) == 0x0001E4, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_GetAccountLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_BooleanAND_ReturnValue) == 0x0001E8, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, CallFunc_Conv_IntToText_ReturnValue) == 0x0001F0, "Member 'FrontEndPartyMember_C_Refresh_Widget::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Refresh_Widget, K2Node_Select2_Default) == 0x000208, "Member 'FrontEndPartyMember_C_Refresh_Widget::K2Node_Select2_Default' has a wrong offset!");

// Function FrontEndPartyMember.FrontEndPartyMember_C.Get Quick Invite Menu
// 0x0028 (0x0028 - 0x0000)
struct FrontEndPartyMember_C_Get_Quick_Invite_Menu final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class UInviteCalloutMenu_C*                   CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FrontEndPartyMember_C_Get_Quick_Invite_Menu) == 0x000008, "Wrong alignment on FrontEndPartyMember_C_Get_Quick_Invite_Menu");
static_assert(sizeof(FrontEndPartyMember_C_Get_Quick_Invite_Menu) == 0x000028, "Wrong size on FrontEndPartyMember_C_Get_Quick_Invite_Menu");
static_assert(offsetof(FrontEndPartyMember_C_Get_Quick_Invite_Menu, ReturnValue) == 0x000000, "Member 'FrontEndPartyMember_C_Get_Quick_Invite_Menu::ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Get_Quick_Invite_Menu, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'FrontEndPartyMember_C_Get_Quick_Invite_Menu::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Get_Quick_Invite_Menu, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'FrontEndPartyMember_C_Get_Quick_Invite_Menu::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(FrontEndPartyMember_C_Get_Quick_Invite_Menu, CallFunc_Create_ReturnValue) == 0x000020, "Member 'FrontEndPartyMember_C_Get_Quick_Invite_Menu::CallFunc_Create_ReturnValue' has a wrong offset!");

}

