#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Necroveil_Shadowplane

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GC_ShadowPlane_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Necroveil_Shadowplane.GC_Necroveil_Shadowplane_C
// 0x0010 (0x0810 - 0x0800)
class AGC_Necroveil_Shadowplane_C final : public AGC_ShadowPlane_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GC_Necroveil_Shadowplane_C;         // 0x0800(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_Necroveil_Shadowplane(int32 EntryPoint);
	void K2_WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, class UParticleSystemComponent* LoopingParticleSystem, const TArray<class UParticleSystemComponent*>& AdditionalParticleSystem);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Necroveil_Shadowplane_C">();
	}
	static class AGC_Necroveil_Shadowplane_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Necroveil_Shadowplane_C>();
	}
};
static_assert(alignof(AGC_Necroveil_Shadowplane_C) == 0x000010, "Wrong alignment on AGC_Necroveil_Shadowplane_C");
static_assert(sizeof(AGC_Necroveil_Shadowplane_C) == 0x000810, "Wrong size on AGC_Necroveil_Shadowplane_C");
static_assert(offsetof(AGC_Necroveil_Shadowplane_C, UberGraphFrame_GC_Necroveil_Shadowplane_C) == 0x000800, "Member 'AGC_Necroveil_Shadowplane_C::UberGraphFrame_GC_Necroveil_Shadowplane_C' has a wrong offset!");

}

