#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_SpellShield

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GC_SpellShield.GC_SpellShield_C.ExecuteUbergraph_GC_SpellShield
// 0x03A8 (0x03A8 - 0x0000)
struct GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget;                             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters;                           // 0x0010(0x00B8)(ContainsInstancedReference)
	class UParticleSystemComponent*               K2Node_Event_RemovalParticleSystem;                // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       K2Node_Event_AdditionalParticleSystems;            // 0x00D0(0x0010)(ZeroConstructor, ReferenceParm)
	class AActor*                                 K2Node_Event_MyTarget2;                            // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters2;                          // 0x00E8(0x00B8)(ContainsInstancedReference)
	class UParticleSystemComponent*               K2Node_Event_LoopingParticleSystem;                // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       K2Node_Event_AdditionalParticleSystem;             // 0x01A8(0x0010)(ZeroConstructor, ReferenceParm)
	class AOrionCharHero*                         K2Node_DynamicCast_AsOrion_Char_Hero;              // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C1[0x7];                                      // 0x01C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AOrionCharHero*                         K2Node_DynamicCast_AsOrion_Char_Hero2;             // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x3];                                      // 0x01D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue; // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue2; // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x01DC(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue2;                  // 0x01E8(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue3;                  // 0x01F4(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue2;         // 0x0204(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue4;                  // 0x0208(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue5;                  // 0x0214(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue3;         // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue4;         // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue6;                  // 0x0228(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetUnscaledCapsuleRadius_ReturnValue;     // 0x0234(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetUnscaledCapsuleRadius_ReturnValue2;    // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue5;         // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue6;         // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0244(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue2;             // 0x0245(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0246(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_247[0x1];                                      // 0x0247(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue7;         // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue7;                  // 0x024C(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue2;          // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x3];                                      // 0x0259(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue8;         // 0x025C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue8;                  // 0x0260(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26C[0x4];                                      // 0x026C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget3;                            // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters3;                          // 0x0278(0x00B8)(ContainsInstancedReference)
	class UParticleSystemComponent*               K2Node_Event_ApplicationParticleSystem;            // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       K2Node_Event_AdditionalParticleSystems2;           // 0x0338(0x0010)(ZeroConstructor, ReferenceParm)
	class UCameraShake*                           K2Node_Event_ApplicationCameraShakeInstance;       // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOrionCharHero*                         K2Node_DynamicCast_AsOrion_Char_Hero3;             // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess3;                      // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_359[0x3];                                      // 0x0359(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetUnscaledCapsuleRadius_ReturnValue3;    // 0x035C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue3; // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue9;         // 0x0364(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue9;                  // 0x0368(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue10;        // 0x0374(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue10;                 // 0x0378(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue11;                 // 0x0384(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue11;        // 0x0390(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue12;                 // 0x0394(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue3;             // 0x03A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue3;          // 0x03A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A2[0x2];                                      // 0x03A2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue12;        // 0x03A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield) == 0x000008, "Wrong alignment on GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield");
static_assert(sizeof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield) == 0x0003A8, "Wrong size on GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, EntryPoint) == 0x000000, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::EntryPoint' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_MyTarget) == 0x000008, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_MyTarget' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_Parameters) == 0x000010, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_RemovalParticleSystem) == 0x0000C8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_RemovalParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_AdditionalParticleSystems) == 0x0000D0, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_AdditionalParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_MyTarget2) == 0x0000E0, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_MyTarget2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_Parameters2) == 0x0000E8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_Parameters2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_LoopingParticleSystem) == 0x0001A0, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_LoopingParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_AdditionalParticleSystem) == 0x0001A8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_AdditionalParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_DynamicCast_AsOrion_Char_Hero) == 0x0001B8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_DynamicCast_AsOrion_Char_Hero' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_DynamicCast_bSuccess) == 0x0001C0, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_DynamicCast_AsOrion_Char_Hero2) == 0x0001C8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_DynamicCast_AsOrion_Char_Hero2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_DynamicCast_bSuccess2) == 0x0001D0, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue) == 0x0001D4, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue2) == 0x0001D8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue) == 0x0001DC, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue2) == 0x0001E8, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue3) == 0x0001F4, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000200, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue2) == 0x000204, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue4) == 0x000208, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue4' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue5) == 0x000214, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue5' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue3) == 0x000220, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue4) == 0x000224, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue4' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue6) == 0x000228, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue6' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_GetUnscaledCapsuleRadius_ReturnValue) == 0x000234, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_GetUnscaledCapsuleRadius_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_GetUnscaledCapsuleRadius_ReturnValue2) == 0x000238, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_GetUnscaledCapsuleRadius_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue5) == 0x00023C, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue5' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue6) == 0x000240, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue6' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Less_FloatFloat_ReturnValue) == 0x000244, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Less_FloatFloat_ReturnValue2) == 0x000245, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Less_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000246, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue7) == 0x000248, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue7' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue7) == 0x00024C, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue7' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Greater_FloatFloat_ReturnValue2) == 0x000258, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Greater_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue8) == 0x00025C, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue8' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue8) == 0x000260, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue8' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_MyTarget3) == 0x000270, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_MyTarget3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_Parameters3) == 0x000278, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_Parameters3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_ApplicationParticleSystem) == 0x000330, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_ApplicationParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_AdditionalParticleSystems2) == 0x000338, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_AdditionalParticleSystems2' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_Event_ApplicationCameraShakeInstance) == 0x000348, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_Event_ApplicationCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_DynamicCast_AsOrion_Char_Hero3) == 0x000350, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_DynamicCast_AsOrion_Char_Hero3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, K2Node_DynamicCast_bSuccess3) == 0x000358, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::K2Node_DynamicCast_bSuccess3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_GetUnscaledCapsuleRadius_ReturnValue3) == 0x00035C, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_GetUnscaledCapsuleRadius_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue3) == 0x000360, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_GetUnscaledCapsuleHalfHeight_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue9) == 0x000364, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue9' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue9) == 0x000368, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue9' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue10) == 0x000374, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue10' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue10) == 0x000378, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue10' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue11) == 0x000384, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue11' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue11) == 0x000390, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue11' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_MakeVector_ReturnValue12) == 0x000394, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_MakeVector_ReturnValue12' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Less_FloatFloat_ReturnValue3) == 0x0003A0, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Less_FloatFloat_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Greater_FloatFloat_ReturnValue3) == 0x0003A1, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Greater_FloatFloat_ReturnValue3' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield, CallFunc_Multiply_FloatFloat_ReturnValue12) == 0x0003A4, "Member 'GC_SpellShield_C_ExecuteUbergraph_GC_SpellShield::CallFunc_Multiply_FloatFloat_ReturnValue12' has a wrong offset!");

// Function GC_SpellShield.GC_SpellShield_C.K2_OnRemove
// 0x00D8 (0x00D8 - 0x0000)
struct GC_SpellShield_C_K2_OnRemove final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UParticleSystemComponent*               RemovalParticleSystem;                             // 0x00C0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       AdditionalParticleSystems;                         // 0x00C8(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(GC_SpellShield_C_K2_OnRemove) == 0x000008, "Wrong alignment on GC_SpellShield_C_K2_OnRemove");
static_assert(sizeof(GC_SpellShield_C_K2_OnRemove) == 0x0000D8, "Wrong size on GC_SpellShield_C_K2_OnRemove");
static_assert(offsetof(GC_SpellShield_C_K2_OnRemove, MyTarget) == 0x000000, "Member 'GC_SpellShield_C_K2_OnRemove::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnRemove, Parameters) == 0x000008, "Member 'GC_SpellShield_C_K2_OnRemove::Parameters' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnRemove, RemovalParticleSystem) == 0x0000C0, "Member 'GC_SpellShield_C_K2_OnRemove::RemovalParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnRemove, AdditionalParticleSystems) == 0x0000C8, "Member 'GC_SpellShield_C_K2_OnRemove::AdditionalParticleSystems' has a wrong offset!");

// Function GC_SpellShield.GC_SpellShield_C.K2_WhileActive
// 0x00D8 (0x00D8 - 0x0000)
struct GC_SpellShield_C_K2_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UParticleSystemComponent*               LoopingParticleSystem;                             // 0x00C0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       AdditionalParticleSystem;                          // 0x00C8(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(GC_SpellShield_C_K2_WhileActive) == 0x000008, "Wrong alignment on GC_SpellShield_C_K2_WhileActive");
static_assert(sizeof(GC_SpellShield_C_K2_WhileActive) == 0x0000D8, "Wrong size on GC_SpellShield_C_K2_WhileActive");
static_assert(offsetof(GC_SpellShield_C_K2_WhileActive, MyTarget) == 0x000000, "Member 'GC_SpellShield_C_K2_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_WhileActive, Parameters) == 0x000008, "Member 'GC_SpellShield_C_K2_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_WhileActive, LoopingParticleSystem) == 0x0000C0, "Member 'GC_SpellShield_C_K2_WhileActive::LoopingParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_WhileActive, AdditionalParticleSystem) == 0x0000C8, "Member 'GC_SpellShield_C_K2_WhileActive::AdditionalParticleSystem' has a wrong offset!");

// Function GC_SpellShield.GC_SpellShield_C.K2_OnActive
// 0x00E0 (0x00E0 - 0x0000)
struct GC_SpellShield_C_K2_OnActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UParticleSystemComponent*               ApplicationParticleSystem;                         // 0x00C0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       AdditionalParticleSystems;                         // 0x00C8(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
	class UCameraShake*                           ApplicationCameraShakeInstance;                    // 0x00D8(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_SpellShield_C_K2_OnActive) == 0x000008, "Wrong alignment on GC_SpellShield_C_K2_OnActive");
static_assert(sizeof(GC_SpellShield_C_K2_OnActive) == 0x0000E0, "Wrong size on GC_SpellShield_C_K2_OnActive");
static_assert(offsetof(GC_SpellShield_C_K2_OnActive, MyTarget) == 0x000000, "Member 'GC_SpellShield_C_K2_OnActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnActive, Parameters) == 0x000008, "Member 'GC_SpellShield_C_K2_OnActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnActive, ApplicationParticleSystem) == 0x0000C0, "Member 'GC_SpellShield_C_K2_OnActive::ApplicationParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnActive, AdditionalParticleSystems) == 0x0000C8, "Member 'GC_SpellShield_C_K2_OnActive::AdditionalParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_SpellShield_C_K2_OnActive, ApplicationCameraShakeInstance) == 0x0000D8, "Member 'GC_SpellShield_C_K2_OnActive::ApplicationCameraShakeInstance' has a wrong offset!");

}

