#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDIndicatorOverlayWidget

#include "Basic.hpp"

#include "HUDIndicatorOverlayWidget_classes.hpp"
#include "HUDIndicatorOverlayWidget_parameters.hpp"


namespace SDK
{

// Function HUDIndicatorOverlayWidget.HUDIndicatorOverlayWidget_C.ExecuteUbergraph_HUDIndicatorOverlayWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUDIndicatorOverlayWidget_C::ExecuteUbergraph_HUDIndicatorOverlayWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDIndicatorOverlayWidget_C", "ExecuteUbergraph_HUDIndicatorOverlayWidget");

	Params::HUDIndicatorOverlayWidget_C_ExecuteUbergraph_HUDIndicatorOverlayWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUDIndicatorOverlayWidget.HUDIndicatorOverlayWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UHUDIndicatorOverlayWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDIndicatorOverlayWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

