#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InventoryItem_Charm

#include "Basic.hpp"

#include "OrionUI_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function InventoryItem_Charm.InventoryItem_Charm_C.ExecuteUbergraph_InventoryItem_Charm
// 0x02B8 (0x02B8 - 0x0000)
struct InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable2;                               // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable3;                               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable4;                               // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable3;                               // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable5;                               // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable6;                               // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInventoryItemDisplayData              K2Node_Event_DisplayData;                          // 0x0010(0x0028)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0038(0x0090)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x00CC(0x0034)(IsPlainOldData, NoDestructor)
	struct FPointerEvent                          K2Node_Event_MouseEvent2;                          // 0x0100(0x0078)()
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerEvent                          K2Node_Event_MouseEvent;                           // 0x0180(0x0078)()
	ESlateVisibility                              Temp_byte_Variable7;                               // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FA[0x6];                                      // 0x01FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush2;                     // 0x0200(0x0090)()
	bool                                          K2Node_Event_bIsSelected;                          // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable8;                               // 0x0291(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bInUse;                               // 0x0292(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select2_Default;                            // 0x0293(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select3_Default;                            // 0x0294(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_295[0x3];                                      // 0x0295(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_NewCount;                             // 0x0298(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable4;                               // 0x029C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29D[0x3];                                      // 0x029D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_Dye;                                  // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Event_DyeTexture;                           // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select4_Default;                            // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm) == 0x000008, "Wrong alignment on InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm");
static_assert(sizeof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm) == 0x0002B8, "Wrong size on InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, EntryPoint) == 0x000000, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::EntryPoint' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_bool_Variable) == 0x000004, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable) == 0x000005, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable2) == 0x000006, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_bool_Variable2) == 0x000007, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable3) == 0x000008, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable4) == 0x000009, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable4' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_bool_Variable3) == 0x00000A, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_bool_Variable3' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable5) == 0x00000B, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable5' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable6) == 0x00000C, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable6' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_DisplayData) == 0x000010, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_DisplayData' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_MakeStruct_SlateBrush) == 0x000038, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, CallFunc_IsValid_ReturnValue) == 0x0000C8, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_MyGeometry) == 0x0000CC, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_MouseEvent2) == 0x000100, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_MouseEvent2' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, CallFunc_GetEndTime_ReturnValue) == 0x000178, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_MouseEvent) == 0x000180, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_MouseEvent' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable7) == 0x0001F8, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable7' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Select_Default) == 0x0001F9, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_MakeStruct_SlateBrush2) == 0x000200, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_MakeStruct_SlateBrush2' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_bIsSelected) == 0x000290, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_bIsSelected' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_byte_Variable8) == 0x000291, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_byte_Variable8' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_bInUse) == 0x000292, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_bInUse' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Select2_Default) == 0x000293, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Select3_Default) == 0x000294, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Select3_Default' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_NewCount) == 0x000298, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_NewCount' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, Temp_bool_Variable4) == 0x00029C, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::Temp_bool_Variable4' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_Dye) == 0x0002A0, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_Dye' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Event_DyeTexture) == 0x0002A8, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Event_DyeTexture' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm, K2Node_Select4_Default) == 0x0002B0, "Member 'InventoryItem_Charm_C_ExecuteUbergraph_InventoryItem_Charm::K2Node_Select4_Default' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.BP_OnDyeLoaded
// 0x0010 (0x0010 - 0x0000)
struct InventoryItem_Charm_C_BP_OnDyeLoaded final
{
public:
	int32                                         Dye;                                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             DyeTexture;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(InventoryItem_Charm_C_BP_OnDyeLoaded) == 0x000008, "Wrong alignment on InventoryItem_Charm_C_BP_OnDyeLoaded");
static_assert(sizeof(InventoryItem_Charm_C_BP_OnDyeLoaded) == 0x000010, "Wrong size on InventoryItem_Charm_C_BP_OnDyeLoaded");
static_assert(offsetof(InventoryItem_Charm_C_BP_OnDyeLoaded, Dye) == 0x000000, "Member 'InventoryItem_Charm_C_BP_OnDyeLoaded::Dye' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_BP_OnDyeLoaded, DyeTexture) == 0x000008, "Member 'InventoryItem_Charm_C_BP_OnDyeLoaded::DyeTexture' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.BP_OnStackCountChanged
// 0x0004 (0x0004 - 0x0000)
struct InventoryItem_Charm_C_BP_OnStackCountChanged final
{
public:
	int32                                         NewCount;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(InventoryItem_Charm_C_BP_OnStackCountChanged) == 0x000004, "Wrong alignment on InventoryItem_Charm_C_BP_OnStackCountChanged");
static_assert(sizeof(InventoryItem_Charm_C_BP_OnStackCountChanged) == 0x000004, "Wrong size on InventoryItem_Charm_C_BP_OnStackCountChanged");
static_assert(offsetof(InventoryItem_Charm_C_BP_OnStackCountChanged, NewCount) == 0x000000, "Member 'InventoryItem_Charm_C_BP_OnStackCountChanged::NewCount' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.BP_OnSetItemInUse
// 0x0001 (0x0001 - 0x0000)
struct InventoryItem_Charm_C_BP_OnSetItemInUse final
{
public:
	bool                                          bInUse;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(InventoryItem_Charm_C_BP_OnSetItemInUse) == 0x000001, "Wrong alignment on InventoryItem_Charm_C_BP_OnSetItemInUse");
static_assert(sizeof(InventoryItem_Charm_C_BP_OnSetItemInUse) == 0x000001, "Wrong size on InventoryItem_Charm_C_BP_OnSetItemInUse");
static_assert(offsetof(InventoryItem_Charm_C_BP_OnSetItemInUse, bInUse) == 0x000000, "Member 'InventoryItem_Charm_C_BP_OnSetItemInUse::bInUse' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.BP_OnSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct InventoryItem_Charm_C_BP_OnSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(InventoryItem_Charm_C_BP_OnSelectionChanged) == 0x000001, "Wrong alignment on InventoryItem_Charm_C_BP_OnSelectionChanged");
static_assert(sizeof(InventoryItem_Charm_C_BP_OnSelectionChanged) == 0x000001, "Wrong size on InventoryItem_Charm_C_BP_OnSelectionChanged");
static_assert(offsetof(InventoryItem_Charm_C_BP_OnSelectionChanged, bIsSelected) == 0x000000, "Member 'InventoryItem_Charm_C_BP_OnSelectionChanged::bIsSelected' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.OnMouseLeave
// 0x0078 (0x0078 - 0x0000)
struct InventoryItem_Charm_C_OnMouseLeave final
{
public:
	struct FPointerEvent                          MouseEvent;                                        // 0x0000(0x0078)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(InventoryItem_Charm_C_OnMouseLeave) == 0x000008, "Wrong alignment on InventoryItem_Charm_C_OnMouseLeave");
static_assert(sizeof(InventoryItem_Charm_C_OnMouseLeave) == 0x000078, "Wrong size on InventoryItem_Charm_C_OnMouseLeave");
static_assert(offsetof(InventoryItem_Charm_C_OnMouseLeave, MouseEvent) == 0x000000, "Member 'InventoryItem_Charm_C_OnMouseLeave::MouseEvent' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.OnMouseEnter
// 0x00B0 (0x00B0 - 0x0000)
struct InventoryItem_Charm_C_OnMouseEnter final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0034)(Parm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0078)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(InventoryItem_Charm_C_OnMouseEnter) == 0x000008, "Wrong alignment on InventoryItem_Charm_C_OnMouseEnter");
static_assert(sizeof(InventoryItem_Charm_C_OnMouseEnter) == 0x0000B0, "Wrong size on InventoryItem_Charm_C_OnMouseEnter");
static_assert(offsetof(InventoryItem_Charm_C_OnMouseEnter, MyGeometry) == 0x000000, "Member 'InventoryItem_Charm_C_OnMouseEnter::MyGeometry' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_OnMouseEnter, MouseEvent) == 0x000038, "Member 'InventoryItem_Charm_C_OnMouseEnter::MouseEvent' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.BP_OnItemSet
// 0x0028 (0x0028 - 0x0000)
struct InventoryItem_Charm_C_BP_OnItemSet final
{
public:
	struct FInventoryItemDisplayData              DisplayData;                                       // 0x0000(0x0028)(ConstParm, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(InventoryItem_Charm_C_BP_OnItemSet) == 0x000008, "Wrong alignment on InventoryItem_Charm_C_BP_OnItemSet");
static_assert(sizeof(InventoryItem_Charm_C_BP_OnItemSet) == 0x000028, "Wrong size on InventoryItem_Charm_C_BP_OnItemSet");
static_assert(offsetof(InventoryItem_Charm_C_BP_OnItemSet, DisplayData) == 0x000000, "Member 'InventoryItem_Charm_C_BP_OnItemSet::DisplayData' has a wrong offset!");

// Function InventoryItem_Charm.InventoryItem_Charm_C.Update Stack Count
// 0x00A8 (0x00A8 - 0x0000)
struct InventoryItem_Charm_C_Update_Stack_Count final
{
public:
	int32                                         Count;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0008(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0050(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0060(0x0018)()
	class FText                                   Temp_text_Variable;                                // 0x0078(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0090(0x0018)()
};
static_assert(alignof(InventoryItem_Charm_C_Update_Stack_Count) == 0x000008, "Wrong alignment on InventoryItem_Charm_C_Update_Stack_Count");
static_assert(sizeof(InventoryItem_Charm_C_Update_Stack_Count) == 0x0000A8, "Wrong size on InventoryItem_Charm_C_Update_Stack_Count");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, Count) == 0x000000, "Member 'InventoryItem_Charm_C_Update_Stack_Count::Count' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, Temp_bool_Variable) == 0x000004, "Member 'InventoryItem_Charm_C_Update_Stack_Count::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, K2Node_MakeStruct_FormatArgumentData) == 0x000008, "Member 'InventoryItem_Charm_C_Update_Stack_Count::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, CallFunc_Greater_IntInt_ReturnValue) == 0x000048, "Member 'InventoryItem_Charm_C_Update_Stack_Count::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, K2Node_MakeArray_Array) == 0x000050, "Member 'InventoryItem_Charm_C_Update_Stack_Count::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, CallFunc_Format_ReturnValue) == 0x000060, "Member 'InventoryItem_Charm_C_Update_Stack_Count::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, Temp_text_Variable) == 0x000078, "Member 'InventoryItem_Charm_C_Update_Stack_Count::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(InventoryItem_Charm_C_Update_Stack_Count, K2Node_Select_Default) == 0x000090, "Member 'InventoryItem_Charm_C_Update_Stack_Count::K2Node_Select_Default' has a wrong offset!");

}

