#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginScreen

#include "Basic.hpp"

#include "OrionUI_classes.hpp"
#include "Engine_structs.hpp"
#include "Account_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LoginScreen.LoginScreen_C
// 0x00A8 (0x0388 - 0x02E0)
class ULoginScreen_C final : public UOrionStateWidget_Login
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       LoginWindowFade_In;                                // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCircularThrobber*                      AsyncLoadingCircularThrobber;                      // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                BorderLogoBackplate;                               // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDefaultButton_C*                       CreateAccountButton;                               // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageBacking;                                      // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageParagon;                                      // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULoginWindow_C*                         LoginWindow;                                       // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDefaultButton_C*                       QuitGameButton;                                    // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDefaultButton_C*                       RunBenchmarkButton;                                // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_0;                                        // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVersionInfo_C*                         VersionInfo;                                       // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	UMulticastDelegateProperty_                   OnAutoLoginStarted;                                // 0x0340(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	UMulticastDelegateProperty_                   OnAutoLoginFinished;                               // 0x0350(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class USoundBase*                             RequestPasswordSound;                              // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             CreateAccountSound;                                // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   EmptyEmail;                                        // 0x0370(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_LoginScreen(int32 EntryPoint);
	void On_EULA_Available(const class FText& EulaText);
	void Construct();
	void BndEvt__CreateAccountButton_K2Node_ComponentBoundEvent_165_OrionBaseButtonClicked__DelegateSignature(class UOrionBaseButton* Button);
	void OnEnterState();
	void BndEvt__LoginWindow_K2Node_ComponentBoundEvent_1_OnForgotPasswordRequest__DelegateSignature(const class FText& Email);
	void OnLoginAuthCodeComplete(ELoginResult Result, const class FText& MESSAGE);
	void OnWebForgotPasswordComplete(bool bSuccess, const class FText& MESSAGE);
	void OnWebCreateAccountComplete(bool bSuccess, const class FText& MESSAGE, const class FString& AuthCode);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void BndEvt__RunBenchmarkButton_K2Node_ComponentBoundEvent_133_OrionBaseButtonClicked__DelegateSignature(class UOrionBaseButton* Button);
	void BndEvt__QuitGameButton_K2Node_ComponentBoundEvent_893_OrionBaseButtonClicked__DelegateSignature(class UOrionBaseButton* Button);
	void BndEvt__LoginWindow_K2Node_ComponentBoundEvent_394_OnLoginRequest__DelegateSignature(const class FText& Username, const class FText& Password, bool RememberMe);
	void OnLoginComplete(ELoginResult Result, const class FText& MESSAGE);
	void OnConfirmed_9B4AE3274E2C73847AC4CD823BF8C098();
	void OnDeclined_9B4AE3274E2C73847AC4CD823BF8C098();
	void OnKilled_9B4AE3274E2C73847AC4CD823BF8C098();
	void OnTimedOut_9B4AE3274E2C73847AC4CD823BF8C098();
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	void Show_Eula(const class FText& EULA_Text);
	void On_Login(ELoginResult Login_Result, const class FText& MESSAGE);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LoginScreen_C">();
	}
	static class ULoginScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoginScreen_C>();
	}
};
static_assert(alignof(ULoginScreen_C) == 0x000008, "Wrong alignment on ULoginScreen_C");
static_assert(sizeof(ULoginScreen_C) == 0x000388, "Wrong size on ULoginScreen_C");
static_assert(offsetof(ULoginScreen_C, UberGraphFrame) == 0x0002E0, "Member 'ULoginScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, LoginWindowFade_In) == 0x0002E8, "Member 'ULoginScreen_C::LoginWindowFade_In' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, AsyncLoadingCircularThrobber) == 0x0002F0, "Member 'ULoginScreen_C::AsyncLoadingCircularThrobber' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, BorderLogoBackplate) == 0x0002F8, "Member 'ULoginScreen_C::BorderLogoBackplate' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, CreateAccountButton) == 0x000300, "Member 'ULoginScreen_C::CreateAccountButton' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, ImageBacking) == 0x000308, "Member 'ULoginScreen_C::ImageBacking' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, ImageParagon) == 0x000310, "Member 'ULoginScreen_C::ImageParagon' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, LoginWindow) == 0x000318, "Member 'ULoginScreen_C::LoginWindow' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, QuitGameButton) == 0x000320, "Member 'ULoginScreen_C::QuitGameButton' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, RunBenchmarkButton) == 0x000328, "Member 'ULoginScreen_C::RunBenchmarkButton' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, SafeZone_0) == 0x000330, "Member 'ULoginScreen_C::SafeZone_0' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, VersionInfo) == 0x000338, "Member 'ULoginScreen_C::VersionInfo' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, OnAutoLoginStarted) == 0x000340, "Member 'ULoginScreen_C::OnAutoLoginStarted' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, OnAutoLoginFinished) == 0x000350, "Member 'ULoginScreen_C::OnAutoLoginFinished' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, RequestPasswordSound) == 0x000360, "Member 'ULoginScreen_C::RequestPasswordSound' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, CreateAccountSound) == 0x000368, "Member 'ULoginScreen_C::CreateAccountSound' has a wrong offset!");
static_assert(offsetof(ULoginScreen_C, EmptyEmail) == 0x000370, "Member 'ULoginScreen_C::EmptyEmail' has a wrong offset!");

}

