#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RegionList

#include "Basic.hpp"


namespace SDK::Params
{

// Function RegionList.RegionList_C.ExecuteUbergraph_RegionList
// 0x0058 (0x0058 - 0x0000)
struct RegionList_C_ExecuteUbergraph_RegionList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_ComponentBoundEvent_Item;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMatchmakingRegion*                     K2Node_DynamicCast_AsMatchmaking_Region;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMatchmakingContext*                    CallFunc_GetContext_ReturnValue;                   // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOrionBaseButton*                       K2Node_ComponentBoundEvent_Button;                 // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMatchmakingContext*                    CallFunc_GetContext_ReturnValue2;                  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SelectRegion_ReturnValue;                 // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(RegionList_C_ExecuteUbergraph_RegionList) == 0x000008, "Wrong alignment on RegionList_C_ExecuteUbergraph_RegionList");
static_assert(sizeof(RegionList_C_ExecuteUbergraph_RegionList) == 0x000058, "Wrong size on RegionList_C_ExecuteUbergraph_RegionList");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, EntryPoint) == 0x000000, "Member 'RegionList_C_ExecuteUbergraph_RegionList::EntryPoint' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, K2Node_ComponentBoundEvent_Item) == 0x000008, "Member 'RegionList_C_ExecuteUbergraph_RegionList::K2Node_ComponentBoundEvent_Item' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, K2Node_DynamicCast_AsMatchmaking_Region) == 0x000010, "Member 'RegionList_C_ExecuteUbergraph_RegionList::K2Node_DynamicCast_AsMatchmaking_Region' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'RegionList_C_ExecuteUbergraph_RegionList::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, K2Node_CreateDelegate_OutputDelegate) == 0x000020, "Member 'RegionList_C_ExecuteUbergraph_RegionList::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'RegionList_C_ExecuteUbergraph_RegionList::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, CallFunc_GetContext_ReturnValue) == 0x000038, "Member 'RegionList_C_ExecuteUbergraph_RegionList::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, K2Node_ComponentBoundEvent_Button) == 0x000040, "Member 'RegionList_C_ExecuteUbergraph_RegionList::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, CallFunc_GetContext_ReturnValue2) == 0x000048, "Member 'RegionList_C_ExecuteUbergraph_RegionList::CallFunc_GetContext_ReturnValue2' has a wrong offset!");
static_assert(offsetof(RegionList_C_ExecuteUbergraph_RegionList, CallFunc_SelectRegion_ReturnValue) == 0x000050, "Member 'RegionList_C_ExecuteUbergraph_RegionList::CallFunc_SelectRegion_ReturnValue' has a wrong offset!");

// Function RegionList.RegionList_C.BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature final
{
public:
	class UOrionBaseButton*                       Button;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature");
static_assert(sizeof(RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature) == 0x000008, "Wrong size on RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature");
static_assert(offsetof(RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'RegionList_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_31_OrionBaseButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function RegionList.RegionList_C.BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature final
{
public:
	class UObject*                                Item;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature) == 0x000008, "Wrong alignment on RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature");
static_assert(sizeof(RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature) == 0x000008, "Wrong size on RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature");
static_assert(offsetof(RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature, Item) == 0x000000, "Member 'RegionList_C_BndEvt__RegionList_K2Node_ComponentBoundEvent_10_ListViewEvent__DelegateSignature::Item' has a wrong offset!");

// Function RegionList.RegionList_C.Fill Region List
// 0x0020 (0x0020 - 0x0000)
struct RegionList_C_Fill_Region_List final
{
public:
	class UMatchmakingContext*                    self2;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMatchmakingRegion*>             CallFunc_GetAvailableRegions_OutRegionOptions;     // 0x0008(0x0010)(ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_GetAvailableRegions_OutSelectedRegion;    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetSelectedIndex_ReturnValue;             // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(RegionList_C_Fill_Region_List) == 0x000008, "Wrong alignment on RegionList_C_Fill_Region_List");
static_assert(sizeof(RegionList_C_Fill_Region_List) == 0x000020, "Wrong size on RegionList_C_Fill_Region_List");
static_assert(offsetof(RegionList_C_Fill_Region_List, self2) == 0x000000, "Member 'RegionList_C_Fill_Region_List::self2' has a wrong offset!");
static_assert(offsetof(RegionList_C_Fill_Region_List, CallFunc_GetAvailableRegions_OutRegionOptions) == 0x000008, "Member 'RegionList_C_Fill_Region_List::CallFunc_GetAvailableRegions_OutRegionOptions' has a wrong offset!");
static_assert(offsetof(RegionList_C_Fill_Region_List, CallFunc_GetAvailableRegions_OutSelectedRegion) == 0x000018, "Member 'RegionList_C_Fill_Region_List::CallFunc_GetAvailableRegions_OutSelectedRegion' has a wrong offset!");
static_assert(offsetof(RegionList_C_Fill_Region_List, CallFunc_SetSelectedIndex_ReturnValue) == 0x00001C, "Member 'RegionList_C_Fill_Region_List::CallFunc_SetSelectedIndex_ReturnValue' has a wrong offset!");

}

