#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TileDataBlock

#include "Basic.hpp"

#include "OrionUI_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Slate_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TileDataBlock.TileDataBlock_C
// 0x0040 (0x03E0 - 0x03A0)
class UTileDataBlock_C final : public UOrionTileDataBlock
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       DarkenTextBar;                                     // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeInText;                                        // 0x03B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Appear;                                            // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 HoverImage;                                        // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_110;                                         // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Strike;                                            // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EHorizontalAlignment                          HorizontalAlignment;                               // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerticalAlignment                            VerticalAlignment;                                 // 0x03D9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EStretch                                      ImageStretch;                                      // 0x03DA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EStretchDirection                             ImageStretchDirection;                             // 0x03DB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TitleTextAnimPlay;                                 // 0x03DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_TileDataBlock(int32 EntryPoint);
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TileDataBlock_C">();
	}
	static class UTileDataBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTileDataBlock_C>();
	}
};
static_assert(alignof(UTileDataBlock_C) == 0x000008, "Wrong alignment on UTileDataBlock_C");
static_assert(sizeof(UTileDataBlock_C) == 0x0003E0, "Wrong size on UTileDataBlock_C");
static_assert(offsetof(UTileDataBlock_C, UberGraphFrame) == 0x0003A0, "Member 'UTileDataBlock_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, DarkenTextBar) == 0x0003A8, "Member 'UTileDataBlock_C::DarkenTextBar' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, FadeInText) == 0x0003B0, "Member 'UTileDataBlock_C::FadeInText' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, Appear) == 0x0003B8, "Member 'UTileDataBlock_C::Appear' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, HoverImage) == 0x0003C0, "Member 'UTileDataBlock_C::HoverImage' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, Image_110) == 0x0003C8, "Member 'UTileDataBlock_C::Image_110' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, Strike) == 0x0003D0, "Member 'UTileDataBlock_C::Strike' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, HorizontalAlignment) == 0x0003D8, "Member 'UTileDataBlock_C::HorizontalAlignment' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, VerticalAlignment) == 0x0003D9, "Member 'UTileDataBlock_C::VerticalAlignment' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, ImageStretch) == 0x0003DA, "Member 'UTileDataBlock_C::ImageStretch' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, ImageStretchDirection) == 0x0003DB, "Member 'UTileDataBlock_C::ImageStretchDirection' has a wrong offset!");
static_assert(offsetof(UTileDataBlock_C, TitleTextAnimPlay) == 0x0003DC, "Member 'UTileDataBlock_C::TitleTextAnimPlay' has a wrong offset!");

}

