#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VaultAwardPopup

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function VaultAwardPopup.VaultAwardPopup_C.ExecuteUbergraph_VaultAwardPopup
// 0x0028 (0x0028 - 0x0000)
struct VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URewardWidget_C*                        K2Node_DynamicCast_AsReward_Widget;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URewardWidget_C*                        K2Node_DynamicCast_AsReward_Widget2;               // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup) == 0x000008, "Wrong alignment on VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup");
static_assert(sizeof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup) == 0x000028, "Wrong size on VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup");
static_assert(offsetof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup, EntryPoint) == 0x000000, "Member 'VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup::EntryPoint' has a wrong offset!");
static_assert(offsetof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup, K2Node_DynamicCast_AsReward_Widget) == 0x000008, "Member 'VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup::K2Node_DynamicCast_AsReward_Widget' has a wrong offset!");
static_assert(offsetof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup, K2Node_DynamicCast_AsReward_Widget2) == 0x000018, "Member 'VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup::K2Node_DynamicCast_AsReward_Widget2' has a wrong offset!");
static_assert(offsetof(VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup, K2Node_DynamicCast_bSuccess2) == 0x000020, "Member 'VaultAwardPopup_C_ExecuteUbergraph_VaultAwardPopup::K2Node_DynamicCast_bSuccess2' has a wrong offset!");

// Function VaultAwardPopup.VaultAwardPopup_C.GetBrush_0
// 0x0090 (0x0090 - 0x0000)
struct VaultAwardPopup_C_GetBrush_0 final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x0090)(Parm, OutParm, ReturnParm)
};
static_assert(alignof(VaultAwardPopup_C_GetBrush_0) == 0x000008, "Wrong alignment on VaultAwardPopup_C_GetBrush_0");
static_assert(sizeof(VaultAwardPopup_C_GetBrush_0) == 0x000090, "Wrong size on VaultAwardPopup_C_GetBrush_0");
static_assert(offsetof(VaultAwardPopup_C_GetBrush_0, ReturnValue) == 0x000000, "Member 'VaultAwardPopup_C_GetBrush_0::ReturnValue' has a wrong offset!");

}

