#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraLens_Blind_Apply

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraLens_Blind_Apply.BP_CameraLens_Blind_Apply_C
// 0x0010 (0x0450 - 0x0440)
class ABP_CameraLens_Blind_Apply_C final : public AEmitterCameraLensEffectBase
{
public:
	class UPostProcessComponent*                  PostProcess;                                       // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CameraLens_Blind_Apply_C">();
	}
	static class ABP_CameraLens_Blind_Apply_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CameraLens_Blind_Apply_C>();
	}
};
static_assert(alignof(ABP_CameraLens_Blind_Apply_C) == 0x000010, "Wrong alignment on ABP_CameraLens_Blind_Apply_C");
static_assert(sizeof(ABP_CameraLens_Blind_Apply_C) == 0x000450, "Wrong size on ABP_CameraLens_Blind_Apply_C");
static_assert(offsetof(ABP_CameraLens_Blind_Apply_C, PostProcess) == 0x000440, "Member 'ABP_CameraLens_Blind_Apply_C::PostProcess' has a wrong offset!");

}

