#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConfirmCancelWidget

#include "Basic.hpp"

#include "ConfirmCancelWidget_classes.hpp"
#include "ConfirmCancelWidget_parameters.hpp"


namespace SDK
{

// Function ConfirmCancelWidget.ConfirmCancelWidget_C.ExecuteUbergraph_ConfirmCancelWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfirmCancelWidget_C::ExecuteUbergraph_ConfirmCancelWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfirmCancelWidget_C", "ExecuteUbergraph_ConfirmCancelWidget");

	Params::ConfirmCancelWidget_C_ExecuteUbergraph_ConfirmCancelWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmCancelWidget.ConfirmCancelWidget_C.HideConfirmWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bImmediate                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConfirmCancelWidget_C::HideConfirmWidget(bool bImmediate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfirmCancelWidget_C", "HideConfirmWidget");

	Params::ConfirmCancelWidget_C_HideConfirmWidget Parms{};

	Parms.bImmediate = bImmediate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmCancelWidget.ConfirmCancelWidget_C.ShowConfirmWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bAllowConfirm                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConfirmCancelWidget_C::ShowConfirmWidget(bool bAllowConfirm)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfirmCancelWidget_C", "ShowConfirmWidget");

	Params::ConfirmCancelWidget_C_ShowConfirmWidget Parms{};

	Parms.bAllowConfirm = bAllowConfirm;

	UObject::ProcessEvent(Func, &Parms);
}

}

