#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CurrencyTotal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CurrencyTotal.CurrencyTotal_C
// 0x0028 (0x0300 - 0x02D8)
class UCurrencyTotal_C final : public UOrionUserWidgetBase
{
public:
	uint8                                         Pad_2D8[0x8];                                      // 0x02D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 ImageIcon;                                         // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOrionTextBlock*                        OrionTextQuantity;                                 // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EOrionCurrencyType                            CurrencyType;                                      // 0x02F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CurrencyTotal(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void HandleCurrencyChanged();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CurrencyTotal_C">();
	}
	static class UCurrencyTotal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurrencyTotal_C>();
	}
};
static_assert(alignof(UCurrencyTotal_C) == 0x000008, "Wrong alignment on UCurrencyTotal_C");
static_assert(sizeof(UCurrencyTotal_C) == 0x000300, "Wrong size on UCurrencyTotal_C");
static_assert(offsetof(UCurrencyTotal_C, UberGraphFrame) == 0x0002E0, "Member 'UCurrencyTotal_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCurrencyTotal_C, ImageIcon) == 0x0002E8, "Member 'UCurrencyTotal_C::ImageIcon' has a wrong offset!");
static_assert(offsetof(UCurrencyTotal_C, OrionTextQuantity) == 0x0002F0, "Member 'UCurrencyTotal_C::OrionTextQuantity' has a wrong offset!");
static_assert(offsetof(UCurrencyTotal_C, CurrencyType) == 0x0002F8, "Member 'UCurrencyTotal_C::CurrencyType' has a wrong offset!");

}

