#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DraftTeam_Enemy

#include "Basic.hpp"


namespace SDK::Params
{

// Function DraftTeam_Enemy.DraftTeam_Enemy_C.ExecuteUbergraph_DraftTeam_Enemy
// 0x0018 (0x0018 - 0x0000)
struct DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMatchmakingContext*                    CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCurrentMatchOfType_ReturnValue;         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy) == 0x000008, "Wrong alignment on DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy");
static_assert(sizeof(DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy) == 0x000018, "Wrong size on DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy");
static_assert(offsetof(DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy, EntryPoint) == 0x000000, "Member 'DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy::EntryPoint' has a wrong offset!");
static_assert(offsetof(DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy, CallFunc_IsCurrentMatchOfType_ReturnValue) == 0x000010, "Member 'DraftTeam_Enemy_C_ExecuteUbergraph_DraftTeam_Enemy::CallFunc_IsCurrentMatchOfType_ReturnValue' has a wrong offset!");

}

