#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicPurchaseFlowDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass EpicPurchaseFlowDisplay.EpicPurchaseFlowDisplay_C
// 0x0028 (0x0258 - 0x0230)
class UEpicPurchaseFlowDisplay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(Transient, DuplicateTransient)
	class UCircularThrobber*                      CircularThrobber_0;                                // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDefaultButton_C*                       CloseButton;                                       // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlap;                                           // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             WebHolder;                                         // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_EpicPurchaseFlowDisplay(int32 EntryPoint);
	void Destruct();
	void BndEvt__CloseButton_K2Node_ComponentBoundEvent_462_OrionBaseButtonClicked__DelegateSignature(class UOrionBaseButton* Button);
	void Dismiss_Widget();
	void Display_Widget(class UWidget* WebWidget, const class FString& OfferId);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EpicPurchaseFlowDisplay_C">();
	}
	static class UEpicPurchaseFlowDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEpicPurchaseFlowDisplay_C>();
	}
};
static_assert(alignof(UEpicPurchaseFlowDisplay_C) == 0x000008, "Wrong alignment on UEpicPurchaseFlowDisplay_C");
static_assert(sizeof(UEpicPurchaseFlowDisplay_C) == 0x000258, "Wrong size on UEpicPurchaseFlowDisplay_C");
static_assert(offsetof(UEpicPurchaseFlowDisplay_C, UberGraphFrame) == 0x000230, "Member 'UEpicPurchaseFlowDisplay_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UEpicPurchaseFlowDisplay_C, CircularThrobber_0) == 0x000238, "Member 'UEpicPurchaseFlowDisplay_C::CircularThrobber_0' has a wrong offset!");
static_assert(offsetof(UEpicPurchaseFlowDisplay_C, CloseButton) == 0x000240, "Member 'UEpicPurchaseFlowDisplay_C::CloseButton' has a wrong offset!");
static_assert(offsetof(UEpicPurchaseFlowDisplay_C, Overlap) == 0x000248, "Member 'UEpicPurchaseFlowDisplay_C::Overlap' has a wrong offset!");
static_assert(offsetof(UEpicPurchaseFlowDisplay_C, WebHolder) == 0x000250, "Member 'UEpicPurchaseFlowDisplay_C::WebHolder' has a wrong offset!");

}

