#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FriendCodePS4

#include "Basic.hpp"

#include "FriendCodePS4_classes.hpp"
#include "FriendCodePS4_parameters.hpp"


namespace SDK
{

// Function FriendCodePS4.FriendCodePS4_C.ExecuteUbergraph_FriendCodePS4
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFriendCodePS4_C::ExecuteUbergraph_FriendCodePS4(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendCodePS4_C", "ExecuteUbergraph_FriendCodePS4");

	Params::FriendCodePS4_C_ExecuteUbergraph_FriendCodePS4 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FriendCodePS4.FriendCodePS4_C.OnSendFriendCodeMessageComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bMessageSent                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UFriendCodePS4_C::OnSendFriendCodeMessageComplete(bool bMessageSent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendCodePS4_C", "OnSendFriendCodeMessageComplete");

	Params::FriendCodePS4_C_OnSendFriendCodeMessageComplete Parms{};

	Parms.bMessageSent = bMessageSent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FriendCodePS4.FriendCodePS4_C.BndEvt__DefaultButton_K2Node_ComponentBoundEvent_57_OrionBaseButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UOrionBaseButton*                 Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFriendCodePS4_C::BndEvt__DefaultButton_K2Node_ComponentBoundEvent_57_OrionBaseButtonClicked__DelegateSignature(class UOrionBaseButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendCodePS4_C", "BndEvt__DefaultButton_K2Node_ComponentBoundEvent_57_OrionBaseButtonClicked__DelegateSignature");

	Params::FriendCodePS4_C_BndEvt__DefaultButton_K2Node_ComponentBoundEvent_57_OrionBaseButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FriendCodePS4.FriendCodePS4_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UFriendCodePS4_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FriendCodePS4_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

