#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Buff_River_MoveSpeed

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GC_Buff_River_MoveSpeed.GC_Buff_River_MoveSpeed_C.ExecuteUbergraph_GC_Buff_River_MoveSpeed
// 0x01D0 (0x01D0 - 0x0000)
struct GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget;                             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters;                           // 0x0010(0x00B8)(ContainsInstancedReference)
	class UParticleSystemComponent*               K2Node_Event_LoopingParticleSystem;                // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       K2Node_Event_AdditionalParticleSystem;             // 0x00D0(0x0010)(ZeroConstructor, ReferenceParm)
	class AOrionCharHero*                         K2Node_DynamicCast_AsOrion_Char_Hero;              // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget2;                            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters2;                          // 0x00F8(0x00B8)(ContainsInstancedReference)
	class UParticleSystemComponent*               K2Node_Event_ApplicationParticleSystem;            // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       K2Node_Event_AdditionalParticleSystems;            // 0x01B8(0x0010)(ZeroConstructor, ReferenceParm)
	class UCameraShake*                           K2Node_Event_ApplicationCameraShakeInstance;       // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed) == 0x000008, "Wrong alignment on GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed");
static_assert(sizeof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed) == 0x0001D0, "Wrong size on GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, EntryPoint) == 0x000000, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::EntryPoint' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_MyTarget) == 0x000008, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_MyTarget' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_Parameters) == 0x000010, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_LoopingParticleSystem) == 0x0000C8, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_LoopingParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_AdditionalParticleSystem) == 0x0000D0, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_AdditionalParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_DynamicCast_AsOrion_Char_Hero) == 0x0000E0, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_DynamicCast_AsOrion_Char_Hero' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_DynamicCast_bSuccess) == 0x0000E8, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_MyTarget2) == 0x0000F0, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_MyTarget2' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_Parameters2) == 0x0000F8, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_Parameters2' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_ApplicationParticleSystem) == 0x0001B0, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_ApplicationParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_AdditionalParticleSystems) == 0x0001B8, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_AdditionalParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed, K2Node_Event_ApplicationCameraShakeInstance) == 0x0001C8, "Member 'GC_Buff_River_MoveSpeed_C_ExecuteUbergraph_GC_Buff_River_MoveSpeed::K2Node_Event_ApplicationCameraShakeInstance' has a wrong offset!");

// Function GC_Buff_River_MoveSpeed.GC_Buff_River_MoveSpeed_C.K2_WhileActive
// 0x00D8 (0x00D8 - 0x0000)
struct GC_Buff_River_MoveSpeed_C_K2_WhileActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UParticleSystemComponent*               LoopingParticleSystem;                             // 0x00C0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       AdditionalParticleSystem;                          // 0x00C8(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(GC_Buff_River_MoveSpeed_C_K2_WhileActive) == 0x000008, "Wrong alignment on GC_Buff_River_MoveSpeed_C_K2_WhileActive");
static_assert(sizeof(GC_Buff_River_MoveSpeed_C_K2_WhileActive) == 0x0000D8, "Wrong size on GC_Buff_River_MoveSpeed_C_K2_WhileActive");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_WhileActive, MyTarget) == 0x000000, "Member 'GC_Buff_River_MoveSpeed_C_K2_WhileActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_WhileActive, Parameters) == 0x000008, "Member 'GC_Buff_River_MoveSpeed_C_K2_WhileActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_WhileActive, LoopingParticleSystem) == 0x0000C0, "Member 'GC_Buff_River_MoveSpeed_C_K2_WhileActive::LoopingParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_WhileActive, AdditionalParticleSystem) == 0x0000C8, "Member 'GC_Buff_River_MoveSpeed_C_K2_WhileActive::AdditionalParticleSystem' has a wrong offset!");

// Function GC_Buff_River_MoveSpeed.GC_Buff_River_MoveSpeed_C.K2_OnActive
// 0x00E0 (0x00E0 - 0x0000)
struct GC_Buff_River_MoveSpeed_C_K2_OnActive final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UParticleSystemComponent*               ApplicationParticleSystem;                         // 0x00C0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       AdditionalParticleSystems;                         // 0x00C8(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
	class UCameraShake*                           ApplicationCameraShakeInstance;                    // 0x00D8(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_Buff_River_MoveSpeed_C_K2_OnActive) == 0x000008, "Wrong alignment on GC_Buff_River_MoveSpeed_C_K2_OnActive");
static_assert(sizeof(GC_Buff_River_MoveSpeed_C_K2_OnActive) == 0x0000E0, "Wrong size on GC_Buff_River_MoveSpeed_C_K2_OnActive");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_OnActive, MyTarget) == 0x000000, "Member 'GC_Buff_River_MoveSpeed_C_K2_OnActive::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_OnActive, Parameters) == 0x000008, "Member 'GC_Buff_River_MoveSpeed_C_K2_OnActive::Parameters' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_OnActive, ApplicationParticleSystem) == 0x0000C0, "Member 'GC_Buff_River_MoveSpeed_C_K2_OnActive::ApplicationParticleSystem' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_OnActive, AdditionalParticleSystems) == 0x0000C8, "Member 'GC_Buff_River_MoveSpeed_C_K2_OnActive::AdditionalParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_Buff_River_MoveSpeed_C_K2_OnActive, ApplicationCameraShakeInstance) == 0x0000D8, "Member 'GC_Buff_River_MoveSpeed_C_K2_OnActive::ApplicationCameraShakeInstance' has a wrong offset!");

}

