#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_CriticallyWounded

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_CriticallyWounded.GC_CriticallyWounded_C
// 0x0020 (0x0790 - 0x0770)
class AGC_CriticallyWounded_C final : public AOrionGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0770(0x0008)(Transient, DuplicateTransient)
	class AActor*                                 TargetActor;                                       // 0x0778(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Strength_Name;                                     // 0x0780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CriticallyWoundedThresholdValue;                   // 0x0788(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LowestStrengthValue;                               // 0x078C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GC_CriticallyWounded(int32 EntryPoint);
	void AdjustStrength();
	void K2_OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, class UParticleSystemComponent* ApplicationParticleSystem, const TArray<class UParticleSystemComponent*>& AdditionalParticleSystems, class UCameraShake* ApplicationCameraShakeInstance);
	void ReceiveTick(float DeltaSeconds);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_CriticallyWounded_C">();
	}
	static class AGC_CriticallyWounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_CriticallyWounded_C>();
	}
};
static_assert(alignof(AGC_CriticallyWounded_C) == 0x000010, "Wrong alignment on AGC_CriticallyWounded_C");
static_assert(sizeof(AGC_CriticallyWounded_C) == 0x000790, "Wrong size on AGC_CriticallyWounded_C");
static_assert(offsetof(AGC_CriticallyWounded_C, UberGraphFrame) == 0x000770, "Member 'AGC_CriticallyWounded_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AGC_CriticallyWounded_C, TargetActor) == 0x000778, "Member 'AGC_CriticallyWounded_C::TargetActor' has a wrong offset!");
static_assert(offsetof(AGC_CriticallyWounded_C, Strength_Name) == 0x000780, "Member 'AGC_CriticallyWounded_C::Strength_Name' has a wrong offset!");
static_assert(offsetof(AGC_CriticallyWounded_C, CriticallyWoundedThresholdValue) == 0x000788, "Member 'AGC_CriticallyWounded_C::CriticallyWoundedThresholdValue' has a wrong offset!");
static_assert(offsetof(AGC_CriticallyWounded_C, LowestStrengthValue) == 0x00078C, "Member 'AGC_CriticallyWounded_C::LowestStrengthValue' has a wrong offset!");

}

