#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Mana_From_Sources

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GC_Mana_From_Sources.GC_Mana_From_Sources_C.ExecuteUbergraph_GC_Mana_From_Sources
// 0x0100 (0x0100 - 0x0000)
struct GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget;                             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters;                           // 0x0010(0x00B8)(ContainsInstancedReference)
	class UParticleSystemComponent*               K2Node_Event_BurstParticleSystems;                 // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       K2Node_Event_AdditionalParticleSystems;            // 0x00D0(0x0010)(ZeroConstructor, ReferenceParm)
	class AOrionChar*                             K2Node_DynamicCast_AsOrion_Char;                   // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x00F4(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources) == 0x000008, "Wrong alignment on GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources");
static_assert(sizeof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources) == 0x000100, "Wrong size on GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, EntryPoint) == 0x000000, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::EntryPoint' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, K2Node_Event_MyTarget) == 0x000008, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::K2Node_Event_MyTarget' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, K2Node_Event_Parameters) == 0x000010, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, K2Node_Event_BurstParticleSystems) == 0x0000C8, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::K2Node_Event_BurstParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, K2Node_Event_AdditionalParticleSystems) == 0x0000D0, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::K2Node_Event_AdditionalParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, K2Node_DynamicCast_AsOrion_Char) == 0x0000E0, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::K2Node_DynamicCast_AsOrion_Char' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, K2Node_DynamicCast_bSuccess) == 0x0000E8, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x0000EC, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000F0, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources, CallFunc_MakeVector_ReturnValue) == 0x0000F4, "Member 'GC_Mana_From_Sources_C_ExecuteUbergraph_GC_Mana_From_Sources::CallFunc_MakeVector_ReturnValue' has a wrong offset!");

// Function GC_Mana_From_Sources.GC_Mana_From_Sources_C.K2_OnExecute
// 0x00D8 (0x00D8 - 0x0000)
struct GC_Mana_From_Sources_C_K2_OnExecute final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	class UParticleSystemComponent*               BurstParticleSystems;                              // 0x00C0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UParticleSystemComponent*>       AdditionalParticleSystems;                         // 0x00C8(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(GC_Mana_From_Sources_C_K2_OnExecute) == 0x000008, "Wrong alignment on GC_Mana_From_Sources_C_K2_OnExecute");
static_assert(sizeof(GC_Mana_From_Sources_C_K2_OnExecute) == 0x0000D8, "Wrong size on GC_Mana_From_Sources_C_K2_OnExecute");
static_assert(offsetof(GC_Mana_From_Sources_C_K2_OnExecute, MyTarget) == 0x000000, "Member 'GC_Mana_From_Sources_C_K2_OnExecute::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_K2_OnExecute, Parameters) == 0x000008, "Member 'GC_Mana_From_Sources_C_K2_OnExecute::Parameters' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_K2_OnExecute, BurstParticleSystems) == 0x0000C0, "Member 'GC_Mana_From_Sources_C_K2_OnExecute::BurstParticleSystems' has a wrong offset!");
static_assert(offsetof(GC_Mana_From_Sources_C_K2_OnExecute, AdditionalParticleSystems) == 0x0000C8, "Member 'GC_Mana_From_Sources_C_K2_OnExecute::AdditionalParticleSystems' has a wrong offset!");

}

