#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_PrimeHelix_PrimaryAttack_Hit_BL

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_PrimeHelix_PrimaryAttack_Hit_BL.GC_PrimeHelix_PrimaryAttack_Hit_BL_C
// 0x0010 (0x05F0 - 0x05E0)
class AGC_PrimeHelix_PrimaryAttack_Hit_BL_C final : public AOrionGameplayCueNotify_Burst_Latent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05E0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_PrimeHelix_PrimaryAttack_Hit_BL(int32 EntryPoint);
	void K2_OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, class UParticleSystemComponent* BurstParticleSystems, const TArray<class UParticleSystemComponent*>& AdditionalParticleSystems);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_PrimeHelix_PrimaryAttack_Hit_BL_C">();
	}
	static class AGC_PrimeHelix_PrimaryAttack_Hit_BL_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_PrimeHelix_PrimaryAttack_Hit_BL_C>();
	}
};
static_assert(alignof(AGC_PrimeHelix_PrimaryAttack_Hit_BL_C) == 0x000010, "Wrong alignment on AGC_PrimeHelix_PrimaryAttack_Hit_BL_C");
static_assert(sizeof(AGC_PrimeHelix_PrimaryAttack_Hit_BL_C) == 0x0005F0, "Wrong size on AGC_PrimeHelix_PrimaryAttack_Hit_BL_C");
static_assert(offsetof(AGC_PrimeHelix_PrimaryAttack_Hit_BL_C, UberGraphFrame) == 0x0005E0, "Member 'AGC_PrimeHelix_PrimaryAttack_Hit_BL_C::UberGraphFrame' has a wrong offset!");

}

