#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_StealSpeedFromBleeding

#include "Basic.hpp"

#include "GC_StealSpeedFromBleeding_classes.hpp"
#include "GC_StealSpeedFromBleeding_parameters.hpp"


namespace SDK
{

// Function GC_StealSpeedFromBleeding.GC_StealSpeedFromBleeding_C.OnExecute
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters&          Parameters                                             (Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGC_StealSpeedFromBleeding_C::OnExecute(class AActor* MyTarget, struct FGameplayCueParameters& Parameters) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_StealSpeedFromBleeding_C", "OnExecute");

	Params::GC_StealSpeedFromBleeding_C_OnExecute Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);

	Parameters = std::move(Parms.Parameters);

	return Parms.ReturnValue;
}

}

