#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Tower_TargetLocked

#include "Basic.hpp"

#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Tower_TargetLocked.GC_Tower_TargetLocked_C
// 0x0000 (0x0770 - 0x0770)
class AGC_Tower_TargetLocked_C final : public AOrionGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Tower_TargetLocked_C">();
	}
	static class AGC_Tower_TargetLocked_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Tower_TargetLocked_C>();
	}
};
static_assert(alignof(AGC_Tower_TargetLocked_C) == 0x000010, "Wrong alignment on AGC_Tower_TargetLocked_C");
static_assert(sizeof(AGC_Tower_TargetLocked_C) == 0x000770, "Wrong size on AGC_Tower_TargetLocked_C");

}

