#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Inhibitor_Projectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Inhibitor_Projectile.Inhibitor_Projectile_C
// 0x0008 (0x0730 - 0x0728)
class AInhibitor_Projectile_C final : public AOrionProjectile
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0728(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Inhibitor_Projectile(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Inhibitor_Projectile_C">();
	}
	static class AInhibitor_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInhibitor_Projectile_C>();
	}
};
static_assert(alignof(AInhibitor_Projectile_C) == 0x000008, "Wrong alignment on AInhibitor_Projectile_C");
static_assert(sizeof(AInhibitor_Projectile_C) == 0x000730, "Wrong size on AInhibitor_Projectile_C");
static_assert(offsetof(AInhibitor_Projectile_C, UberGraphFrame) == 0x000728, "Member 'AInhibitor_Projectile_C::UberGraphFrame' has a wrong offset!");

}

