#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayRoot

#include "Basic.hpp"

#include "PlayRoot_classes.hpp"
#include "PlayRoot_parameters.hpp"


namespace SDK
{

// Function PlayRoot.PlayRoot_C.ExecuteUbergraph_PlayRoot
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayRoot_C::ExecuteUbergraph_PlayRoot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "ExecuteUbergraph_PlayRoot");

	Params::PlayRoot_C_ExecuteUbergraph_PlayRoot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayRoot.PlayRoot_C.OnDeactivated
// (Event, Protected, BlueprintEvent)

void UPlayRoot_C::OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayRoot.PlayRoot_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPlayRoot_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayRoot.PlayRoot_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPlayRoot_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "PreConstruct");

	Params::PlayRoot_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayRoot.PlayRoot_C.BndEvt__Button_Solo_K2Node_ComponentBoundEvent_44_OrionSelectedStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UOrionBaseButton*                 Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Selected                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPlayRoot_C::BndEvt__Button_Solo_K2Node_ComponentBoundEvent_44_OrionSelectedStateChanged__DelegateSignature(class UOrionBaseButton* Button, bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "BndEvt__Button_Solo_K2Node_ComponentBoundEvent_44_OrionSelectedStateChanged__DelegateSignature");

	Params::PlayRoot_C_BndEvt__Button_Solo_K2Node_ComponentBoundEvent_44_OrionSelectedStateChanged__DelegateSignature Parms{};

	Parms.Button = Button;
	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayRoot.PlayRoot_C.BndEvt__Button_Coop_K2Node_ComponentBoundEvent_26_OrionSelectedStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UOrionBaseButton*                 Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Selected                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPlayRoot_C::BndEvt__Button_Coop_K2Node_ComponentBoundEvent_26_OrionSelectedStateChanged__DelegateSignature(class UOrionBaseButton* Button, bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "BndEvt__Button_Coop_K2Node_ComponentBoundEvent_26_OrionSelectedStateChanged__DelegateSignature");

	Params::PlayRoot_C_BndEvt__Button_Coop_K2Node_ComponentBoundEvent_26_OrionSelectedStateChanged__DelegateSignature Parms{};

	Parms.Button = Button;
	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayRoot.PlayRoot_C.BndEvt__Button_PvP_K2Node_ComponentBoundEvent_9_OrionSelectedStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UOrionBaseButton*                 Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Selected                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPlayRoot_C::BndEvt__Button_PvP_K2Node_ComponentBoundEvent_9_OrionSelectedStateChanged__DelegateSignature(class UOrionBaseButton* Button, bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "BndEvt__Button_PvP_K2Node_ComponentBoundEvent_9_OrionSelectedStateChanged__DelegateSignature");

	Params::PlayRoot_C_BndEvt__Button_PvP_K2Node_ComponentBoundEvent_9_OrionSelectedStateChanged__DelegateSignature Parms{};

	Parms.Button = Button;
	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayRoot.PlayRoot_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UPlayRoot_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayRoot.PlayRoot_C.UpdateRegion
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPlayRoot_C::UpdateRegion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayRoot_C", "UpdateRegion");

	UObject::ProcessEvent(Func, nullptr);
}

}

