#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PostGame_Header

#include "Basic.hpp"


namespace SDK::Params
{

// Function PostGame_Header.PostGame_Header_C.ExecuteUbergraph_PostGame_Header
// 0x0004 (0x0004 - 0x0000)
struct PostGame_Header_C_ExecuteUbergraph_PostGame_Header final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PostGame_Header_C_ExecuteUbergraph_PostGame_Header) == 0x000004, "Wrong alignment on PostGame_Header_C_ExecuteUbergraph_PostGame_Header");
static_assert(sizeof(PostGame_Header_C_ExecuteUbergraph_PostGame_Header) == 0x000004, "Wrong size on PostGame_Header_C_ExecuteUbergraph_PostGame_Header");
static_assert(offsetof(PostGame_Header_C_ExecuteUbergraph_PostGame_Header, EntryPoint) == 0x000000, "Member 'PostGame_Header_C_ExecuteUbergraph_PostGame_Header::EntryPoint' has a wrong offset!");

}

