#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StylizedDivider_Vert_ArrowDir

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum StylizedDivider_Vert_ArrowDir.StylizedDivider_Vert_ArrowDir
// NumValues: 0x0004
enum class EStylizedDivider_Vert_ArrowDir : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	StylizedDivider_Vert_MAX                 = 3,
};

}

