#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_Body_Cancel

#include "Basic.hpp"

#include "TextStyle_Base_Cancel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Body-Cancel.TextStyle-Body-Cancel_C
// 0x0000 (0x0258 - 0x0258)
class UTextStyle_Body_Cancel_C final : public UTextStyle_Base_Cancel_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Body-Cancel_C">();
	}
	static class UTextStyle_Body_Cancel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_Body_Cancel_C>();
	}
};
static_assert(alignof(UTextStyle_Body_Cancel_C) == 0x000008, "Wrong alignment on UTextStyle_Body_Cancel_C");
static_assert(sizeof(UTextStyle_Body_Cancel_C) == 0x000258, "Wrong size on UTextStyle_Body_Cancel_C");

}

