#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VictoryDefeatScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OrionGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass VictoryDefeatScreen.VictoryDefeatScreen_C
// 0x0060 (0x0390 - 0x0330)
class UVictoryDefeatScreen_C final : public UOrionHUDVictoryScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       Victory_Defeat;                                    // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Color_Change;                                      // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Impact_Smoke;                                // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_LanguageGlyphs;                              // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Pattern;                                     // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_RadialStroke;                                // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Text_Blur;                                   // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             LoseText;                                          // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             WinText;                                           // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	UMulticastDelegateProperty_                   NewEventDispatcher_0;                              // 0x0380(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_VictoryDefeatScreen(int32 EntryPoint);
	void ShowDefeat();
	void ShowVictory();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VictoryDefeatScreen_C">();
	}
	static class UVictoryDefeatScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVictoryDefeatScreen_C>();
	}
};
static_assert(alignof(UVictoryDefeatScreen_C) == 0x000008, "Wrong alignment on UVictoryDefeatScreen_C");
static_assert(sizeof(UVictoryDefeatScreen_C) == 0x000390, "Wrong size on UVictoryDefeatScreen_C");
static_assert(offsetof(UVictoryDefeatScreen_C, UberGraphFrame) == 0x000330, "Member 'UVictoryDefeatScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Victory_Defeat) == 0x000338, "Member 'UVictoryDefeatScreen_C::Victory_Defeat' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Color_Change) == 0x000340, "Member 'UVictoryDefeatScreen_C::Color_Change' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Image_Impact_Smoke) == 0x000348, "Member 'UVictoryDefeatScreen_C::Image_Impact_Smoke' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Image_LanguageGlyphs) == 0x000350, "Member 'UVictoryDefeatScreen_C::Image_LanguageGlyphs' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Image_Pattern) == 0x000358, "Member 'UVictoryDefeatScreen_C::Image_Pattern' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Image_RadialStroke) == 0x000360, "Member 'UVictoryDefeatScreen_C::Image_RadialStroke' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, Image_Text_Blur) == 0x000368, "Member 'UVictoryDefeatScreen_C::Image_Text_Blur' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, LoseText) == 0x000370, "Member 'UVictoryDefeatScreen_C::LoseText' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, WinText) == 0x000378, "Member 'UVictoryDefeatScreen_C::WinText' has a wrong offset!");
static_assert(offsetof(UVictoryDefeatScreen_C, NewEventDispatcher_0) == 0x000380, "Member 'UVictoryDefeatScreen_C::NewEventDispatcher_0' has a wrong offset!");

}

